-- Singers INSERT statements
-- Generated from scraping data

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE singers;
SET FOREIGN_KEY_CHECKS=1;

INSERT IGNORE INTO singers (singer_name) VALUES ('& KK');
INSERT IGNORE INTO singers (singer_name) VALUES ('(Female)');
INSERT IGNORE INTO singers (singer_name) VALUES ('.');
INSERT IGNORE INTO singers (singer_name) VALUES ('.Mp3');
INSERT IGNORE INTO singers (singer_name) VALUES ('1 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('2 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('3 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('A.R Ameen');
INSERT IGNORE INTO singers (singer_name) VALUES ('AR Rahman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aarthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aavani Malhar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Abhijith Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Achu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Adanan Sami');
INSERT IGNORE INTO singers (singer_name) VALUES ('Adithya Iyengar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditi Bhavaraju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditi Bhavaraju & Ramya Behara');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditi Shankar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditi Singh Sharma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditya Iyenagar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditya Iyengar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aditya Iyengar & Prudhvi Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Adnan Sami');
INSERT IGNORE INTO singers (singer_name) VALUES ('Adviteeya Vojjala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Airaa Udupi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aishwarya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aishwarya Ravichan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aishwarya Ravichandran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ajay Atul');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ajay-Atul');
INSERT IGNORE INTO singers (singer_name) VALUES ('Akasa Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Akashdeep Sengupta');
INSERT IGNORE INTO singers (singer_name) VALUES ('Akhil Akkineni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Akhil Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Alap Raju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Allu Arjun');
INSERT IGNORE INTO singers (singer_name) VALUES ('Alphons Joseph');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amala Chebolu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amalraj & Priya Himesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amit Mishra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amit Trivedi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amitabh Bachchan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Amito');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anaida & Mark Lazaro');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anand Aravindakshan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anandhu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anandi Joshi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ananthu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ananya Bhat');
INSERT IGNORE INTO singers (singer_name) VALUES ('Andrea');
INSERT IGNORE INTO singers (singer_name) VALUES ('Andrea Jeremiah');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anirudh Ravichander');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anirudh Ravichander & Srinidhi Venkatesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anitha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anjana Soumya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anjana Sowmy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anoushka');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anthony Daasan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anudeep Dev');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anudeep Devarakonda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anup Rubens');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anup Rubens & Dhanunjay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anup Rubens & Kailash Kher');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anuraag Kulkarni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anuradha Sriram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anurag Kulakarni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anurag Kulkarni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anurag Kulkarni & Geetha Madhuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anurag kulkarni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Anushka Manchanda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aparna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aparna Nandan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aravind Srinivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arijit Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arjun Chandy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Armaan Malik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arun Gopan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arun Kaundinya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arun Kaundinyas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arun Koundinya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arun kaundinya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Aruna Sairam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Arunraja Kamaraj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Asal Kolaar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ashwini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Asura');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ayyan Pranathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('B Praak');
INSERT IGNORE INTO singers (singer_name) VALUES ('B. Ajneesh Loknath');
INSERT IGNORE INTO singers (singer_name) VALUES ('B.Ajaneesh Loknath');
INSERT IGNORE INTO singers (singer_name) VALUES ('Baba Seghal & Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('Baba Sehgal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Baby Anusha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Badshah');
INSERT IGNORE INTO singers (singer_name) VALUES ('Balakrishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bappi Lahiri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bashermax');
INSERT IGNORE INTO singers (singer_name) VALUES ('Belly Raj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Benny Dayal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bgm –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bharath Raj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bhargavi Pillai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bhaskarbhatla Ravikumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bhavana Isvi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bheems Ceciroleo');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bhole');
INSERT IGNORE INTO singers (singer_name) VALUES ('Blaaze');
INSERT IGNORE INTO singers (singer_name) VALUES ('Blazee');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bobo Shashi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bolt');
INSERT IGNORE INTO singers (singer_name) VALUES ('Bombay Jayashree');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brahmanandam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brijesh Shandiliya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brijesh Shandilya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brinda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brodha V');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brunda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Brundham');
INSERT IGNORE INTO singers (singer_name) VALUES ('Burra Kadha –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chaitan Bharadwaj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chaitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chaitra Ambadipudi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chakri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chakri & Bobby &  Chaks & Yadagiri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chakri & Kousalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chakri & Setha Pandit');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chakri & Thina Kamal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chandana Bala Kalyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chandra Bose');
INSERT IGNORE INTO singers (singer_name) VALUES ('Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Charu Hariharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Child Singers Group');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinmayi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinmayi & jaspreet Jasz');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinmayi Sripaada');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinmayi Sripada');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinmayi sripada');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinna Ponnu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chinnaponnu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chitra & Jassie Gift');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chitra & Tippu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chitra & Tippu & Vijji');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chorus');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chorus Version) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Chowrasta Band');
INSERT IGNORE INTO singers (singer_name) VALUES ('Christopher Stanley');
INSERT IGNORE INTO singers (singer_name) VALUES ('Cizzy');
INSERT IGNORE INTO singers (singer_name) VALUES ('D. Velmurugan');
INSERT IGNORE INTO singers (singer_name) VALUES ('DJ Vasanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('DSP');
INSERT IGNORE INTO singers (singer_name) VALUES ('Daamani & Srikanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Daler Mehendi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Daler Mehndi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Damini Batla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Damini Batla Ch');
INSERT IGNORE INTO singers (singer_name) VALUES ('Damini Bhatla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Danunjay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Darshan Raval');
INSERT IGNORE INTO singers (singer_name) VALUES ('David SImon');
INSERT IGNORE INTO singers (singer_name) VALUES ('David Simon');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepak');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepak & Hari Priya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepak Blue');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepthi Parthasaradhy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepthi Parthasarathy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepti');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepu & Karunya & Kausalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Deepu & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Devan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Devi Sri Prasad');
INSERT IGNORE INTO singers (singer_name) VALUES ('Devi Sri Prasad & Mamatha Mohandoss');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhananjay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhanunjay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhanunjay Seepana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dharuni Rajyasampada – Kuruvruddhol – Kaarunkoothalu) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhee');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhinakar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhinkchakkacha –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhivya Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhruv Vikram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dhvani Bhanushali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Diljit Dosanjh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dinesh Kanaga Rathinam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dinkar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dinker');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divija Karthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divija Karthic');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divija Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya Diwakar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya Kumar & M M Manasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya Malika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya S Menon');
INSERT IGNORE INTO singers (singer_name) VALUES ('Divya Spandana (Ramya)');
INSERT IGNORE INTO singers (singer_name) VALUES ('Diya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Download');
INSERT IGNORE INTO singers (singer_name) VALUES ('Downoad
Singers :- Sathyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Dr. Arun Gopan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Elvya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Emcee Jaze');
INSERT IGNORE INTO singers (singer_name) VALUES ('Farhan Akhtar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Farid');
INSERT IGNORE INTO singers (singer_name) VALUES ('Feroz Israel');
INSERT IGNORE INTO singers (singer_name) VALUES ('Franko');
INSERT IGNORE INTO singers (singer_name) VALUES ('G.V. Prakash Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('GV Prakash Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganesh Ram PS');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganga');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganga & Deepu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganga & Kushi Murali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganga & Mallikarjuna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganga & Udit Narayana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganjawala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gannora Dasa Laxmi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ganta Venkata Lakshmi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gantadi Krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geeath Madurai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geeta Madhuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geetha Madhuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geetha Madhuri & Nani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geetha Madhuri & Narendhra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Geethamadhuri & Hema Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Georgina Matthew');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ghantasala –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ghibran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gomathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gopi Sundar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gopi Sunder');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gopika Poornima');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gopika Poornima & Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gopika Purnima');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gotte Kanakavva');
INSERT IGNORE INTO singers (singer_name) VALUES ('Goutham Bharadwaj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Govind Vasantha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Govinda Vasantha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gowtham Bharadwaj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gowtham Bharadwaj V');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gowtham bharadwaj V');
INSERT IGNORE INTO singers (singer_name) VALUES ('Guru Randhawa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Gv Prakash Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haniya Nafisa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hanuman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hard Kaur');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hari');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hari Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hari Haran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hari Priya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hari Teja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haricharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haricharan & Harini Sudhakar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haricharan Seshadri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hariharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hariharan & Nanditha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hariharan & Sujatha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hariharasudhan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harika Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harika Narayanan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harika Naryan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harini & Jeevan Sreenivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harini Ivaturi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harini Ivvaturi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harini Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haripriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haripriya & Aravind Srinivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harish Raghavendra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harish Sivaramakrishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Haritha Balakrishnan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harsha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harsha D');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harshavardhan Rameshwar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Harshika Gudi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hem Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hema Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hema Chandra & Geetha Madhuru & Suchitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('HemaChandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra & Malavika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra & Mark Antony Thomas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra & Narendra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra & Sniggy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandra Vedala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hemachandran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hesham Abdul Wahab');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hip Hop Tamizha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hiphop Tamizha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Honey');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hymanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hymath');
INSERT IGNORE INTO singers (singer_name) VALUES ('Hymath Mohammed');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ilaiyaraja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Indravathi Chauhan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Inno Genga');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ishaq Vali');
INSERT IGNORE INTO singers (singer_name) VALUES ('JKV');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jagadeesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jai Srinivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jakes Bejoy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Janaki Iyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Janani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jaspreet Jasz');
INSERT IGNORE INTO singers (singer_name) VALUES ('Javed Ali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jayadev');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jessi Gist');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jithin');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jithin Raj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Joanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jonita Gandhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jr NTR');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jr NTR & Mamatha Mohandas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jubin Nautiyal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Justin Prabhakaran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jyoti Nooran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Jyotsna');
INSERT IGNORE INTO singers (singer_name) VALUES ('K G Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('K S Chitra & S P Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('K. J. Yesudas');
INSERT IGNORE INTO singers (singer_name) VALUES ('K. Pranati');
INSERT IGNORE INTO singers (singer_name) VALUES ('K. S. Chithra');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.G.Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.K');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.K & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.K.');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.Pranati');
INSERT IGNORE INTO singers (singer_name) VALUES ('K.S.Chithra');
INSERT IGNORE INTO singers (singer_name) VALUES ('KK');
INSERT IGNORE INTO singers (singer_name) VALUES ('KK & Benny Dayal');
INSERT IGNORE INTO singers (singer_name) VALUES ('KS Chitra & Madhusree');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kaala Bhairava');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kailash Kher');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kala Bhairava');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kalapana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kalpana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kalpana Raghavendar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kalyan Vasanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kalyani Malik & Malgudi Subha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kanakavva');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kanika Kapoor & Mika Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kapil');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kapil Kapian');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kapil Kapilan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kapil Kapilan & Haripriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kareemulla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karrimullah');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Anuradha Sriram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Chinmayi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Kalpana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Mahalakshmi Lyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Manikk Vinayagam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Rita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Sapna Aswathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Shalini Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik & Vardhani Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik Raja & Swarnalatha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthik Rodriguez');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthikeya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karthikeyan MLR');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karuna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Karunya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kashyap');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kausalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kausalya & Rajesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kavitha Subramanyam & Udit Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Keerthana Sharma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Keerthana Srinivasan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Keerthana Vaidyanathan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kiran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kj Yesudas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Koti Saluri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kousalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kousalya & Ajay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kousalya & Hariharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kousalya & Shankar mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kousalya & Sp Balu & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Krishna Tejasvi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Krishnamaraju & Pradeep');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ks Chitra & Babji');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ks Chitra & Jessi Gift');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kumar Sanu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kumara Vagdevi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kummari Durgavva');
INSERT IGNORE INTO singers (singer_name) VALUES ('Kunal');
INSERT IGNORE INTO singers (singer_name) VALUES ('L V Revanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('L. V. Revanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('LV Revanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lakshmi Meghna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lavita Lobo');
INSERT IGNORE INTO singers (singer_name) VALUES ('Laxmi Dasa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Leela –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Leslie');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lipsika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lipsika & Dhanunjay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lipsika  Bhashaym');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lloyd Paul');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lokesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lokeshwar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Lynn');
INSERT IGNORE INTO singers (singer_name) VALUES ('M Ashirwad Luke');
INSERT IGNORE INTO singers (singer_name) VALUES ('M G Srikumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('M L Shruti');
INSERT IGNORE INTO singers (singer_name) VALUES ('M M Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('M M Keeravani & Kavitha Krishnamurthy');
INSERT IGNORE INTO singers (singer_name) VALUES ('M M Keeravani & Sunitha Upadrastha');
INSERT IGNORE INTO singers (singer_name) VALUES ('M M Manasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('M. Haripriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('M. L. R Karthikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('M. L. R. Karthikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('M. M. Keeravaani');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.L.R. Karthikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.L.R. Karthikeyan & Ranina Reddy');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.L.R.Karthikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.M Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.M. Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.M. Keeravani & Ganga');
INSERT IGNORE INTO singers (singer_name) VALUES ('M.M. Keeravani & Sunitha');
INSERT IGNORE INTO singers (singer_name) VALUES ('MC Hari');
INSERT IGNORE INTO singers (singer_name) VALUES ('MC Vickey');
INSERT IGNORE INTO singers (singer_name) VALUES ('MG Srikumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('ML Gayathri');
INSERT IGNORE INTO singers (singer_name) VALUES ('ML Shruti');
INSERT IGNORE INTO singers (singer_name) VALUES ('ML Sruthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('MLR Karthikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('MLR Kartikeyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('MM Keeravaani');
INSERT IGNORE INTO singers (singer_name) VALUES ('MM Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('MM Manasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('MM Sreelekha');
INSERT IGNORE INTO singers (singer_name) VALUES ('MM Srilekha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maahaa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maalathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maayalatho Janiyinchi) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhavi Ravuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhu Bala Krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhu Priya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhu Shree');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhubanti Bagchi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Madhumita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahalakshmi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahalakshmi & karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahalakshmi Iyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahalingam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahati Swara Sagar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mahesh Kathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Malathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Malavika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Malavika Manoj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Malavika Manoj and Srimadumita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mallikarjun');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mallikarjuna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mallikarjuna & Sunitha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mallikarjuna Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mallikharjuna Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mamta Sharma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manasa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manasi M.M.');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manasi MM');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manasi Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maneesh Pandranki');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maneesha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maneesha Pandranki');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mangli');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mangli
Lyricist :- Kasarla Shyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mani Nagaraj & Kausalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mani Sharma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manikya Vinayagan & Anuradha Sriram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manikyam Vinayakam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manish Dinakar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manish Eerabathini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manisha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manisha Eerabathini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manisha Eerabhathini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manishi Musugulo');
INSERT IGNORE INTO singers (singer_name) VALUES ('Manju Sri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mano');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mano & Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mano & Gango');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mano & Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mano & R P Patnaik & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mansi Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mantra Anand');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maria Roe');
INSERT IGNORE INTO singers (singer_name) VALUES ('Maruthi Kodimoju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Masnisha errabathini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Master Rishon Rubens');
INSERT IGNORE INTO singers (singer_name) VALUES ('Matin');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mc Vickey');
INSERT IGNORE INTO singers (singer_name) VALUES ('Megastar Chiranjeevi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Megha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Megha & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Megha Sravanthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mika Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mixed –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohammed Abid Ali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohan Bhogaraju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohan Dass');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohan Krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohana Bhogaraju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohana Bhograj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mohit Chauhan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Monisha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mounika Yadav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mounima');
INSERT IGNORE INTO singers (singer_name) VALUES ('Moushimi Neha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Mukesh & Suchitra Karthik Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Murali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Muralidhar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Muralidhar & Ganga');
INSERT IGNORE INTO singers (singer_name) VALUES ('N C Karunya');
INSERT IGNORE INTO singers (singer_name) VALUES ('N.S. Ramya');
INSERT IGNORE INTO singers (singer_name) VALUES ('NTR & Rita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nadapriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nagakanya Paadutondi –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nagarjuna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nakash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nakash Aziz');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nakul Abhaynkar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nakul Abhyankar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Namitha Babu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nandita Jyothi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Narasanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Narendra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naresh Iyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naresh Mamindla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naresh mamindla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Narsanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Natalie Di Luccio');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nava Rasa Suma Maalika –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naveen');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naveen & Jyotsna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Naveen Madhav & Rita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Navin Madhav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Navraj Hans');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nayana Nair');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nazim Arshad & Anwar Saadath');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nc Karunya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Neeti Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Neha Bashin & Vijay Prakash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Neha Bhasin');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nihal & Mani Nagaraj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nikhita Gandhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nikhitha Gandhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nikita Nigam & Sandeep Chowta');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nikitha Gandhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nikitha Srivalli');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nilayini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nilayini & Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('Niranj Suresh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Niranjana Ramanan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nsk Ramya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nutana Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Nuthana Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Olammo Orayyo –');
INSERT IGNORE INTO singers (singer_name) VALUES ('P V N S Rohit');
INSERT IGNORE INTO singers (singer_name) VALUES ('PVNS Rohit');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padma Latha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padmalatha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padyam –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padyam – 3 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padyam – 4 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padyam – 5 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Padyam – 6 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Palamuru Jangireddy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Parag Chhabra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Parama Yogulu –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Parampara Tandon');
INSERT IGNORE INTO singers (singer_name) VALUES ('Parnika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Paroma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pathos –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pavithra Chari');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pawan Kalyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pekata Paparao –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Penchal Das');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pooja Vaidyanath');
INSERT IGNORE INTO singers (singer_name) VALUES ('Poojan Kohli');
INSERT IGNORE INTO singers (singer_name) VALUES ('Poornima');
INSERT IGNORE INTO singers (singer_name) VALUES ('Poorvi Koutish');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prabhu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prabhu Pandala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pradeep Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prakash Raj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prakruthi Reddy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranati');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranavi & Daler Mehndi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranavi & Mano');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranavi & Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranavi Acharya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pranayama –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prashanth R Vihari');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prashantini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pratyusha pallapothu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Praveen Lakkaraju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pravina Selvi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Preeti Pillai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prem Gi Amaren');
INSERT IGNORE INTO singers (singer_name) VALUES ('Premgi Amaren');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prithvi Chandhra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priya Hamesh & Baba Sehgal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priya Hemesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priya Himesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priya Ragu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priya sisters');
INSERT IGNORE INTO singers (singer_name) VALUES ('Priyadarshini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prudhvi Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prudhvi Sruthi Ranjani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Prudvi Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Puneeth Rudranag');
INSERT IGNORE INTO singers (singer_name) VALUES ('Punya Srinivas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Purushasooktham (Vedic Chanting)) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pushpavanam Kuppuswamy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Pvns Rohit');
INSERT IGNORE INTO singers (singer_name) VALUES ('R P Patnaik & Kausalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('R P Patnaik & Kausalya & Nihal');
INSERT IGNORE INTO singers (singer_name) VALUES ('R P Patnaik & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raajulakey Raraju');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raashi Khanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rabbit Mac');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rachitha rayaprolu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Radhika & Murali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raghu Dixit');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raghu Kunche');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raghu Ram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raghuram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiar & Dharmana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiar & Geetha Madhuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiar & Naveen Madhav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiar & Ranjith & Naveen Madhav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Nambiyar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Ramakrishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Sipliganj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rahul Sipligunj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raja Kumari');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rajasekhar Pannala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rajesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rajesh & Nanditha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rajesh & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ram Gopal Varma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ram Miriyala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ram Pothineni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramachari');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramajogayya Sastry');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramana Gogula');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramana Gogula & Suneetha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rambabu Gosala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya & Rita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya Behara');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya Behera');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya Behra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya Mehra & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya NSK');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya behara');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ramya behra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranina Reddy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranina Reddy & Daler Mehndi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith & Anushka Manchanda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith & Chinmayi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith & Naveen Madhav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith & Saindhavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith &  Roshini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith Govind');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith KG');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ranjith Unni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rap Rock Shakeel');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raquib');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rashi Khanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Barsur');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Basrur');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Basrur Team');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi G');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Teja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Teja &  M.M.Manasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Varma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravi Varma & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Raviteja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ravivarma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rela Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Renu Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Revanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Revanth LV');
INSERT IGNORE INTO singers (singer_name) VALUES ('Revathi & Remo Fernandes');
INSERT IGNORE INTO singers (singer_name) VALUES ('Revathi Mannava');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rita & Bhargavi Pillai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rita & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rita Thygarajan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ritesh G Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rohini Soratt');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rohini Sorrat');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rohit Paritala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rohith');
INSERT IGNORE INTO singers (singer_name) VALUES ('Roll Rida');
INSERT IGNORE INTO singers (singer_name) VALUES ('Roshini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rp Patnaik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Rp Patnaik & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Abhsek & Deepak');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P B & Sujatha & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Bala Subramanayam & Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P BalaSubramanyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Balasubramanyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Balasubramanyam & Gopika Purnima');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('S P Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S S Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('S S Thaman & Bindhu Mahima');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. Aishwarya');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. Aishwarya & S. Soundarya');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. P. B. Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. P. Balasubrahmanyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. P. Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. Riya Seepana');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. Soundarya & Sruthi Ranjani');
INSERT IGNORE INTO singers (singer_name) VALUES ('S. Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P Balasubramanyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P. Abhishek');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P. Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P. Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P.B & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.P.Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.S. Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.p Bala Subramanyam');
INSERT IGNORE INTO singers (singer_name) VALUES ('S.p Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('SP Balasubramanyam & Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('SP Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('SS Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saaki Srinivas & Barimisetty');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saathanakhaagra) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sachet Tandon');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sachin Balu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sachin Basrur');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sadhana Sargam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sagar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sagar & Haripriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sahithi Chaganti');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sahithi Galidevara');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sahiti');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sahiti Chaganti');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Charan & Prudhvi Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Charan Bhaskaruni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Geethika');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sai Shilpa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saicharan Bhaskaruni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saindhavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saindhavi & Ranjith & Hema Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sakesth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saket Bairoliya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saketh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saketh Komanduri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Salman Khan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saloni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sam CS');
INSERT IGNORE INTO singers (singer_name) VALUES ('Samantha Fernander');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sameer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sameera');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sameera Bharadwaj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sandeep Chowta');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sandhya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sandilya Pisapati');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sangeetha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sangeetha & Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sangeetha Rajeswaran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjana & Deepak');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjana Kalamanje');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjana Kalamanje/span>');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjana Kalmanje');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sanjith Hegde');
INSERT IGNORE INTO singers (singer_name) VALUES ('Santhosh Narayanan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Santhosh Venky');
INSERT IGNORE INTO singers (singer_name) VALUES ('Santosh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Santosh Hariharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('SantoshG');
INSERT IGNORE INTO singers (singer_name) VALUES ('Saranya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sarath Santhosh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sarvepalli Sisters');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sathya Prakash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sathya Prakash & Chinmayi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sathya Yamini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sathyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Satya Yamini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Satyan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Satyavathi Mangli');
INSERT IGNORE INTO singers (singer_name) VALUES ('Savitha Sai');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sean Roldan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sekhar');
INSERT IGNORE INTO singers (singer_name) VALUES ('SenSongs –');
INSERT IGNORE INTO singers (singer_name) VALUES ('SenSongsMp3');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shaan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shabir');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shahid Mallya');
INSERT IGNORE INTO singers (singer_name) VALUES ('ShakthiSree Gopalan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shakthisree Gopalan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shakthisree Gopalan & Brodha V');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shalini Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shalmali Kholgade');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar Mahadevan & Premgi Amaren');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar Mahadevan & Rahul Nambiar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar Mahadevan & Rimmi Tommy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar Mahadevan & Sunidhi Chauhan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar mahadevan & Chitra Lyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankar mahadevan & Gayatri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shankarr Babu Kandukoori');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shanmukha Priya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sharvi Yadav');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shashaa');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shashaa Tirupati');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shashaa Tirupati & Yazin Nizar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shekhar Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shekhar Ravjiani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shilpa Rao');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shiva Naagulu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shiva Nirvana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shivam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shivani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shivaradhaya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shobana Chandrakumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shravana Bhargavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & KK');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & Kanul Ganjawala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & Mano');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & Shankar mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & Udith Narayana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghosal & udith Nayarana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Ghoshal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shreya Jayadeep');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shruthi Ranjani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shruti Haasan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shruti Pathak');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shweta Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Shweta Pandit');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sid Sriram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Siddharth Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Siddharth Mahadevan & Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Siddharth Mahadevan & Shivam Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Siddharth Watkins');
INSERT IGNORE INTO singers (singer_name) VALUES ('Siddu Jonnalagadda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sidhu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Silambarasan (Simbu)');
INSERT IGNORE INTO singers (singer_name) VALUES ('Simbu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Simha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Simha & Hanuman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sindhuja Srinivasan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sinduri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sinduri Vishal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sithara Krishnakumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sivani Saraswatula');
INSERT IGNORE INTO singers (singer_name) VALUES ('Smita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Smita & Sree Kalyana Rama');
INSERT IGNORE INTO singers (singer_name) VALUES ('Smitha & Mallikarjuna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Snigdha Sharma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Snigdha Sharma & Gomathi Iyer');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sniggy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Solo –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Song – Dialogues –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sonia');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sonu Kakkar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sonu Kakkar & Divya Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sonu Kakkar & Pradip Somasundaran');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sonu Nigam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sony');
INSERT IGNORE INTO singers (singer_name) VALUES ('Soon');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sooraj Santhosh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sooranna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Soujanya Bhagavathula');
INSERT IGNORE INTO singers (singer_name) VALUES ('Soundarya Sakalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sowmya Raoh & Jaspret Jasz');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sp Bala Subramanya & Charan & ganga');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sp Bala Subramanyam & Chitra & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sp Balu & Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sp Balu & Harini & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Spandana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Spoorthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Spoorthi Jithender');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sravana Bharagavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sravana Bhargavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sree');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreedeep.K');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreehari K.');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreenidhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreenidhi Tirumala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreerama Chandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreerama Chandra Mynampati');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sreya Ghoshal');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri & Kalpana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Dhruthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Kommineni');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Krishna & Geetha Madhuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Soumya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Soumya Varanasi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Sowmya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri Vidya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sri krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sricharan Pakala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srikanth');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srikrishana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srikrishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srilekha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srilekha Parthysarthi & Jessie Gift');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srimadhumita');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srimathumitha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinidhi & Ajesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinidhi Tirumala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinidhi Venkatesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinisha J');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinisha Jayas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srinivas Chakravarthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sriramachandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srivaradhi & Malathi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srivardhini & Hari Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srivarthini & Udit Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Srividhya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sriya Madury');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sruthi Ranjani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sruthi Ranjani & Sri Krishna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sruthi Ranjani Pratyusha pallapothu & Harika Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sthothram –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Stony Psyko');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sublahshini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchetha Basrur');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra Karthik & Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra Karthik Kuamr & Girl Simbu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra Karthik Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra Karthik Kumar & Javed Ali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchitra Karthik Kumar & Mika Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suchtra & Shankar Mahadevan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sudha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sudhamayi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sudharshan Ashok');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sujatha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sujatha & Mano');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sujatha Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sujatha Mohan & Ravi Varma');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sujitha & Charan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sukhwinder Singh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sumangali');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sumangaly');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunder C Babu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunidhi Chauhan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunil');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunil Kashyap');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Sarath');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Sarath and Abhay');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Sarathy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Upadrastha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Upadrastha & Keeravani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Upadrastha & Udith Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunitha Updrastha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sunny M.R.');
INSERT IGNORE INTO singers (singer_name) VALUES ('Supriya Joshi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suraj');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suresh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suresh Bobbili');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suresh Peter');
INSERT IGNORE INTO singers (singer_name) VALUES ('Suriya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Surya Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swarag');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swarag Keerthan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swarnalatha & Mano');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swaroopa Reddy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swathi Reddy UK');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swathireddy UK');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sweekar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sweekar Agasthi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sweeker');
INSERT IGNORE INTO singers (singer_name) VALUES ('Sweta Subramanian');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swetha Mohan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swetha Pandit');
INSERT IGNORE INTO singers (singer_name) VALUES ('Swetha pandit & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tanishk Bagchi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tanvi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tanvi Shah & Devan Ekambaram');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tanvi Shash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Teja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Telangana Sakuntala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thaman S');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thaman S.');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thaman S. & Rahul Nambiar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Theme 2 –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Theme Music –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Theme –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thirepamettina – Madhavamaayatho – Gandharava Pathi – Marathune – Dharma Nirathishakthiga) –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Thirupathi Matla');
INSERT IGNORE INTO singers (singer_name) VALUES ('Timmy');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tippu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tippu & Chitra & Suresh Peters');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tippu & Harini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tippu & Kalyani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tippu & Srivaradhi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tipu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Title Song –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tppu & Kowshalya & Suneetha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Travis King');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tulsi Kumar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Tushar Joshi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Udit Narayan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Udit Narayan & Kausalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Udit Narayan & Kousalya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Uma Neha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Umaneha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Urukulaparuguladora – Nethaalalera –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Usha');
INSERT IGNORE INTO singers (singer_name) VALUES ('Usha & Karthik');
INSERT IGNORE INTO singers (singer_name) VALUES ('Usha & Rajesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Usha Uthup');
INSERT IGNORE INTO singers (singer_name) VALUES ('Uyyayini Roy');
INSERT IGNORE INTO singers (singer_name) VALUES ('V Srisoumya');
INSERT IGNORE INTO singers (singer_name) VALUES ('V. M. Mahalingam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vaasu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vagdevi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vaishnavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vaishnavi Kovvuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vaishnavi kovvuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vandana Srinivasan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Varam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vardhani Thaman');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vardhini');
INSERT IGNORE INTO singers (singer_name) VALUES ('Varikuppala Yadagiri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Various');
INSERT IGNORE INTO singers (singer_name) VALUES ('Various Artist');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vedala Hemachandra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vedhala hema Chandra & Saindhavi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vel Murugan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Venkatesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Venky');
INSERT IGNORE INTO singers (singer_name) VALUES ('Venu');
INSERT IGNORE INTO singers (singer_name) VALUES ('Venu & Ulaganathan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Viashnavi Kovvuri');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vidhu Pratap');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vidya Sagar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vidya Vox');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Antony');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Devarakonda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Devarakonda (Extra Song – Not In Album)');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Deverakonda');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Prakash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay PrakashSingers');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Yesudas');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay Yesudas & Suchitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijay prakash');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vijaynarain');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vikjay Yesudas & Raqueed Alam');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vikram Montrose');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vimalakka');
INSERT IGNORE INTO singers (singer_name) VALUES ('Violin Bits –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishaadam –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishal Chandra Sekhar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishal Dadlani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishal Mishra');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishal-Shekhar & Vishal Dadlani');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishnu Priya');
INSERT IGNORE INTO singers (singer_name) VALUES ('Vishnupriya Ravi');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yadhu Krishnan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yadu Krishnan K');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yallinti Ramana');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yamini & Rajesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yamini Ghantasala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yazin Nizar');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yazin Nizar & Priya Himesh');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yazin Nizar & Ramya Behera');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yemini Ghantasala');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yepuri Somanna');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yugala Geetam –');
INSERT IGNORE INTO singers (singer_name) VALUES ('Yuvan Shankar Raja');
INSERT IGNORE INTO singers (singer_name) VALUES ('Zahrah Khan');
INSERT IGNORE INTO singers (singer_name) VALUES ('Ziya ul Haq');
INSERT IGNORE INTO singers (singer_name) VALUES ('karthik & Ks Chitra');
INSERT IGNORE INTO singers (singer_name) VALUES ('kausalya & Hariharan');
INSERT IGNORE INTO singers (singer_name) VALUES ('manisha');
INSERT IGNORE INTO singers (singer_name) VALUES ('thaman S');
INSERT IGNORE INTO singers (singer_name) VALUES ('u – Leader – Anirudh Ravichander');
