-- Albums INSERT statements
-- Generated from Pagal World scraper

INSERT IGNORE INTO albums (
    title, language, description, thumbnail_url, year,
    director, music_director, star_cast, created_at, updated_at
) VALUES
(
    'Bandi Padhyodi',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564987/4564987.jpg',
    2024,
    '',
    'Shambhu Meena, Vaishali Rajkor',
    '',
    NOW(),
    NOW()
),
(
    'Crakk Jeetegaa Toh Jiyegaa',
    'hindi',
    '',
    'https://pagalworldmusic.com/downloads/cover/4564644/4564644.jpg',
    2024,
    NULL,
    'Various Artists',
    NULL,
    NOW(),
    NOW()
),
(
    'Dange',
    'hindi',
    '',
    'https://pagalworldmusic.com/downloads/cover/4564840/4564840.jpg',
    2024,
    NULL,
    'Sanjith Hegde, Dhruv Visvanath, Gaurav Godkhindi',
    NULL,
    NOW(),
    NOW()
),
(
    'Dil Ki Baat',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564750/4564750.jpg',
    2024,
    '',
    'Rashmi Nishad, Mukesh Choudhary',
    '',
    NOW(),
    NOW()
),
(
    'Fagan Mein Gori Nache',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564926/4564926.jpg',
    2024,
    '',
    'Happy Singh, Bablu Ankiya, Mahadev Studio',
    '',
    NOW(),
    NOW()
),
(
    'Ghar Gavadi Laje Pivar Sasro',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564986/4564986.jpg',
    2024,
    '',
    'Dinesh Dewasi, Isha Bhati, Shaitan Mewadi',
    '',
    NOW(),
    NOW()
),
(
    'Good Morning DJ Remix',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564752/4564752.jpg',
    2024,
    '',
    'Prakash Dewasi, Jyoti Sen, Mukesh Choudhary, DJ Bheru Amet',
    '',
    NOW(),
    NOW()
),
(
    'Kaagaz 2',
    'hindi',
    '',
    'https://c.saavncdn.com/626/Merry-Christmas-Hindi-2024-20240216161930-500x500.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Kako Layo Kakdi Dj Remix',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564751/4564751.jpg',
    2024,
    '',
    'Ojasvi Geeta Goswami, Jai Vaishnav, DJ Bheru Amet',
    '',
    NOW(),
    NOW()
),
(
    'Mami Aaja Khela Fagan Me',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564826/4564826.jpg',
    2024,
    '',
    'Shyam Bidiyasar, Rinku Sharma',
    '',
    NOW(),
    NOW()
),
(
    'Merry Christmas',
    'hindi',
    '',
    'https://pagalworldmusic.com/downloads/cover/4564653/4564653.jpg',
    2024,
    NULL,
    'Pritam',
    NULL,
    NOW(),
    NOW()
),
(
    'Nakharali Dewasan',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564749/4564749.jpg',
    2024,
    '',
    'Bablu Ankiya, Sonu Kanwar, Dinesh Silgava',
    '',
    NOW(),
    NOW()
),
(
    'Pichkari Ro Pani',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564754/4564754.jpg',
    2024,
    '',
    'Jyoti Sen',
    '',
    NOW(),
    NOW()
),
(
    'Pivar Java De',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564930/4564930.jpg',
    2024,
    '',
    'Vaishali Rajkor, Dinesh Lohar',
    '',
    NOW(),
    NOW()
),
(
    'Raghunandana (From HanuMan) Hindi',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564654/4564654.jpg',
    2024,
    '',
    'Saicharan Bhaskaruni, Lokeshwar Edara, Harshavardhan Chavali, GowraHari',
    '',
    NOW(),
    NOW()
),
(
    'Ram Se Mera (feat. Saurabh Gujjar  Nancy Rathore)',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564914/4564914.jpg',
    2024,
    '',
    'Harjeet Deewana, Mintu Bhardwaj',
    '',
    NOW(),
    NOW()
),
(
    'Rupyo Automatic',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564828/4564828.jpg',
    2024,
    '',
    'Sharwan Racheti, Rakhi Rangili',
    '',
    NOW(),
    NOW()
),
(
    'Singles',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/default.webp',
    NULL,
    '',
    '',
    '',
    NOW(),
    NOW()
),
(
    'Tera Kya Hoga Lovely',
    'hindi',
    '',
    'https://c.saavncdn.com/409/Tera-Kya-Hoga-Lovely-Hindi-2024-20240304160948-500x500.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Yeh Pal Hain Apne (From Dange)',
    'hindi',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/4564645/4564645.jpg',
    2024,
    '',
    'Dhruv Visvanath',
    '',
    NOW(),
    NOW()
);

