-- Albums INSERT statements
-- Generated from scraping data with data cleanup

INSERT IGNORE INTO albums (title, year, director, music_director, star_cast, thumbnail_url) VALUES
('1947 A Love Story', 2011, 'Vijay.L', 'G.V.Prakash Kumar', 'Arya, Amy Jackson', 'https://sensongsmp3.live/wp-content/uploads/2016/12/1947-A-Love-Story-Telugu-mp3-Songs.jpg'),
('@Nartanasala', 2018, 'Srinivas Chakravarthi', 'Mahati Swara Sagar', 'Naga Shaurya,Kashmira, Yamini Bhaskar', 'https://sensongsmp3.live/wp-content/uploads/2018/08/Nartanasala-2018-telugu-mp3-download-free.jpg'),
('A', 1998, 'Upendra', 'Gurukiran', 'Upendra, Chandini, Archana', 'https://sensongsmp3.live/wp-content/uploads/2015/03/A-1998-telugu-movie-songs-sensongsmp3co.jpg'),
('A AA', 2016, 'Trivikram Srinivas', 'Mickey J Meyer', 'Nithin, Samantha, Ananya, Anupama Parameswaran', 'https://sensongsmp3.live/wp-content/uploads/2016/05/a-aa-telugu-mp3-songs-download-sensongsmp3co.jpg'),
('A Aa E Eee', 2009, 'Srinivas Reddy', 'M.M.Srelekha', 'Srikanth, Sadha. Meera Jasmine', 'https://sensongsmp3.live/wp-content/uploads/2015/04/A-Aa-E-Ee-songs.jpeg'),
('A.K. Rao P.K. Rao', 2014, 'Kotapati Sreenu', 'Kotapati Sreenu', 'Dhanraj, Shrusti, Daksha, Ramesh', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Ak-Rao-Pk-Rao-Telugu-mp3-Songs.jpg'),
('A1 Express', 2021, 'Dennis Jeevan Kanukolanu', 'HipHop Tamizha', 'Sundeep Kishan, Lavanya Tripathi', 'https://sensongsmp3.live/wp-content/uploads/2021/02/a1-express-songs-2021-sundeep-kishan-lavanya-tripathi.jpg'),
('ABCD', 2019, 'Sanjeev Reddy', 'Judah Sandhy', 'Allu Sirish, Rukshar Dhillon', 'https://sensongsmp3.live/wp-content/uploads/2019/02/ABCD-American-Born-Confused-Desi-2019-telugu-movie-songs.jpg'),
('ARM (2024) – Telugu', 2024, 'Jithin Laal', 'Dhibu Ninan Thomas', 'Tovino Thomas, Krithi Shetty', 'https://sensongsmp3.live/wp-content/uploads/2024/11/ARM-Songs.jpg'),
('Aa Ammayi Gurinchi Meeku Cheppali', 2022, 'Mohana Krishna Indraganti', 'Vivek Sagar', 'Sudheer Babu, Krithi Shetty', 'https://sensongsmp3.live/wp-content/uploads/2022/09/Aa-Ammayi-Gurinchi-Cheppali-songs.jpeg'),
('Aa Intlo', 2009, 'Chinna', 'Koti', 'Chinna, Asha Saini', 'https://sensongsmp3.live/wp-content/uploads/2017/02/aa-intlo-jpeg-sensongs-mp3.jpg'),
('Aa Naluguru', 2004, 'Chandra Siddartha', 'R.P.Patnaik', 'Rajendra Prasad, Aamani', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aa-Naluguru-songs.jpeg'),
('Aa Okkadu', 2009, 'N S Murthy', 'Mani Sharma', 'Ajay, Madhurima', 'https://sensongsmp3.live/wp-content/uploads/2017/02/aa-okkadu-jpeg-sensongs-mp3.jpg'),
('Aa Okkati Adakku', 2024, 'Malli Ankam', 'Gopi Sunder', 'Allari Naresh, Faria Abdullah', 'https://sensongsmp3.live/wp-content/uploads/2024/03/Aa-Okkati-Adakku-2024-songs.jpg'),
('Aadabrathuku', 1965, 'Vedantam Raghaviah', 'Viswanathan Rama Murthy', 'NT Rama Rao, Devika', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aadabrathuku-1965-telugu-movie-songs-ntr.jpeg'),
('Aadadhe Aadharam', 1987, 'Vissu', 'Sankar Ganesh', 'Chandra Mohan, Seetha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aadadhe-Aadharam-1987jpeg.jpg'),
('Aadalla Mazaaka', 1995, 'Muthyala Subbaiah', 'Vandemataram Srinivas', 'Anand, Ooha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aadalla-Mazaaka-1995jpeg.jpg'),
('Aadambaralu Anubandhalu', 1974, 'C S Rao', 'K Chakravarthy', 'Krishan, Saradha', 'https://sensongsmp3.live/wp-content/uploads/2015/12/Aadambaralu-Anubandhalu-1974-songs-download.jpg'),
('Aadante Adotypu', 2003, 'E.V.V.Satyanarayana', 'Yuvan Shankar Raaja', 'Aryan Rajesh, Sindhu Menon', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aadante-Adotypu-2003-songs.jpeg'),
('Aadapaduchu', 1986, 'A Mohan Gandhi', 'Rajan Nagendra', 'Sivakrishna, Poornima', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aadapaduchu-1986jpeg.png'),
('Aadarsha Kutumbam', 1969, 'Kolli Pratyagatma', 'Saluri Rajeswara Rao', 'Akkineni Nageshwara Rao, Anjali Devi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aadarsha-Kutumbam-1969-Jpeg-Sensongs-mp3.jpg'),
('Aadavaallaku Maatrame', 1994, 'Singeetam Srinivasa Rao', 'Ilaiyaraaja', 'Nassar, Revathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aadavaallaku-Maatrame-1994jpeg.jpg'),
('Aadavari Matalaku Ardhale Verule', 2007, 'Sri Raghava', 'Yuvan Shankar Raja', 'Venkatesh, Trisha', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aadavari-Matalaku-Ardhale-Verule-songs-venkatesh.jpeg'),
('Aadhi Dampathulu', 1987, NULL, 'Satyam', 'Akkineni Nageswara Rao, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aadhi-Dampathulu-1987jpeg.jpg'),
('Aadhi Lakshmi', 2006, 'Y.Suresh', 'Chakri', 'Srikanth, Vadde Naveen, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aadhi-Lakshmi-songs.jpeg'),
('Aadi', 2002, 'V V Vinayak', 'Mani Sharma', 'Jr NTR & Keerthy Chawla', 'https://sensongsmp3.live/wp-content/uploads/2016/09/aadhi-telugu-sensongsmp3.jpg'),
('Aadikeshava', 2023, 'Srikanth Reddy', 'G V Prakash Kumar', 'Vaishnav Tej, Shree Leela', 'https://sensongsmp3.live/wp-content/uploads/2023/09/Aadikeshava-2023-songs-download-adikeshava-sreeleela.jpg'),
('Aadivishnu', 2008, 'Bhrath Parapally', 'M.M.Srikekha', 'Dasari Arun, Sneha', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aadivishnu-songs.jpeg'),
('Aadu Magaadra Bujji', 2013, 'Krishna Reddy', 'Sri Kommineni', 'Sudheer Babu,Asmita Sood', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Aadu-Magaadra-Bujji-Telugu-mp3-Songs.jpg'),
('Aagadu Mp3 Songs', NULL, 'Sreenu Vaitla', 'S S Thaman', 'Mahesh Babu, Tamanna', 'https://sensongsmp3.live/wp-content/uploads/2016/07/aagadu-sensongsmp3.jpg'),
('Aagraham', 1991, 'K S Ravi Kumar', 'Raj Koti', 'Rajasekhar, Amala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aagraham-1991jpeg.jpg'),
('Aaha', 1998, 'Suresh Krishna', 'Vandemataram Srinivas', 'Jagapathi Babu, Sanghavi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aaha-1998jpegsensongs-mp3.jpg'),
('Aaha Entha Andam', 2010, 'Jaya Murugan', 'Jeevan Thomas', 'Jai Akash, Nicole', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Aaha-Entha-Andam-Telugu-mp3-Songs.jpg'),
('Aaha Kalyanam', 2014, 'Gokul Krishna', 'Dharan Kumar', 'Nani, Vaani kapoor', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Aaha-Kalyanam-Telugu-mp3-Songs.jpg'),
('Aahuthi', 1988, 'Kodi Rama Krishna', 'Satyam', 'Rajasekhar, Jeevitha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aahuthi-1988-Jpegsensongs-mp3.jpg'),
('Aahwanam', 1997, NULL, 'S.V.Krishna Reddy', 'Srikanth, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aahwanam-1997jpegsensongsmp3.jpg'),
('Aakaasam Nee Haddhu Ra Songs', 2020, 'Sudha Kongara', 'G.V. Prakash Kumar', 'Suriya, Aparna Balamurali', 'https://sensongsmp3.live/wp-content/uploads/2020/11/Aakaasam-Nee-Haddhu-Ra-songs-download.jpg'),
('Aakali Rajyam', 1981, 'K.Balachander', 'M. S. Viswanathan', 'Kamal Haasan, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aakali-Rajyam-1981jpegsensongsmp3.jpg'),
('Aakarshana', 1986, NULL, 'Ilaiyaraaja', 'Karthik, Saranya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aakarshana-1986jpeg.jpg'),
('Aakasa Ramanna', 1965, 'G Viswanathan', 'SP Kodandapani', 'Kanta Rao, Rajasree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aakasa-Ramanna-jpeg.jpg'),
('Aakasa Veedhullo', 2021, 'Gautham Krishna', 'Judah Sandhy', 'Gautham Krishna, Pujita Ponnada', 'https://sensongsmp3.live/wp-content/uploads/2021/04/Aakasa-Veedhullo-songs-2021-sid-sriram.jpg'),
('Aakasamantha', 2009, 'Radha Mohan', 'Vidyasagar', 'Prakash Raj, Trisha', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Aakasamantha-jpeg-sensongs-mp3.jpg'),
('Aakasame Haddu', 2011, 'Ravi Charan Meripo', 'Anand', 'Navadeep, Panch Bora', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Aakasame-Haddu-Telugu-mp3-Songs.jpg'),
('Aakasamlo Oka Tara', 2026, 'Pavan Sadineni', 'GV Prakash Kumar', 'Dulquer Salmaan', 'https://sensongsmp3.live/wp-content/uploads/2025/12/Aakasamlo-Oka-Tara-Songs-298x180.jpg'),
('Aakashavaani', 2021, 'Ashwin Gangaraju', 'Kaala Bhairava', 'P.Samuthirakani, Vinay Varma, Teja Kakumanu, Prashant', 'https://sensongsmp3.live/wp-content/uploads/2021/07/Aakashavani-2021.jpg'),
('Aakatayi', 2017, 'Rom Bhimana', 'Mani Sharma', 'Ashish Raj, Rukshar Mir', 'https://sensongsmp3.live/wp-content/uploads/2017/02/aakathayi-songs-sensongsmp3.jpg'),
('Aakhari Poratam', 1988, 'K.Ragavendra Rao', 'Ilayaraja', 'Nagarjuna, Sridevi, Suhasini', 'https://sensongsmp3.live/wp-content/uploads/2017/01/aakariporatam-jpeg.jpg-songs.jpg'),
('Aalapana', 1985, 'Vamsy', 'Ilaiyaraaja', 'Mohan, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/aalapana-1985-jpegsensongs-mp3.jpg'),
('Aalasyam Amrutham', 2010, 'Chandra Mahesh', 'Koti', 'Nikhil, Madalasa Sharma', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Aalasyam-Amrutham-Telugu-mp3-Songs.jpg'),
('Aalaya Sikharam', 1983, 'Kodi Rama Krishna', 'Satyam C', 'Chiranjeevi, Sumalatha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aalaya-Sikharam-1983jpegsensongs-mp3.jpg'),
('Aalu Magalu', 1959, 'Krishna Rao', 'K V Mahadevan', 'Jaggayya, Sowcar Janaki', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aalu-Magalu-1959jpeg.jpg'),
('Aame', 1994, 'E.V.V.Satyanarayana', 'Vidyasagar', 'Srikanth, Ooha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aame-1994jpeg-Sensongs-mp3.jpg'),
('Aame Athadaithe', 2016, 'Surya Naryana K', 'Yaho Krishnan', 'Hanish, Chirasri', 'https://sensongsmp3.live/wp-content/uploads/2017/04/Aame-Athadaithe-2016jpegsensongsmp3.jpg'),
('Aame Evaru', 1966, 'S. Narayan', 'Veda', 'Jaggayya, Vanisree, Jayalalitha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aame-Evaru-1966jpeg.jpg'),
('Aame Kapuram', 1994, NULL, 'Ilaiyaraaja', 'Prasanth, Ooha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aame-Kapuram-1994jpeg.jpg'),
('Aame Katha', 1977, 'K Raghavendra Rao', 'K Chakravarthy', 'Murali Mohan, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aame-Katha-1977jpeg.jpg'),
('Aanandha Thaandavam', 2009, 'A.R.Gandhi Krishna', 'G.V.Prakash Kumar', 'Rishi, Tamanna', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Aanandha-Thaandavam-jpeg-sensongs-mp3.jpg'),
('Aaptha Mithrulu', 1963, 'K.B.Nagabhsanam', 'Ghantasala', 'N T Rama Rao, Krishna Kumari', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aaptha-Mithrulu-1963jpeg.jpg'),
('Aaradhana', 1976, 'B.V.Prasad', 'Saluri Hemantha Rao', 'N T Rama Rao, Vanisri', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aaradhana-1976jpegsensongsmp3.jpg'),
('Aaradugula Bellet', 2017, 'Mani Sharma', NULL, 'Gopichand, Nayanatara', 'https://sensongsmp3.live/wp-content/uploads/2017/06/Aarudugula-Bullet-2017-Movie.jpg'),
('Aarani Mantalu', 1980, 'K Vasu', 'Satyam', 'Chiranjeevi, Kavitha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aarani-Mantalu-1980jpeg.jpg'),
('Aaro Pranam', 1997, NULL, 'K.Veeru', 'Vineeth, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aaro-Pranam-1997jpegsensongs-mp3.jpg'),
('Aarthanadam', 1988, 'M Raghu', 'Hamsalekha', 'Rajasekhar, Seetha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aarthanadam-1988jpeg.jpg'),
('Aaru', 2005, 'Hari', 'Devi Sri Prasad', 'Surya, Trisha', 'https://sensongsmp3.live/wp-content/uploads/2016/11/aaru-songs-SenSongsMp3.jpg'),
('Aasajeevulu', 1962, 'B S Ranga', NULL, 'Relangi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aasajeevulu-1962jpeg.jpg'),
('Aasthiparulu', 1966, 'V.Madhusudhan Rao', 'K.V.Mahadevan', 'Akkineni Nageshwara Rao, Jayalalitha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aasthiparulu-1966jpegsensongsmp3.jpg'),
('Aasthulu Anthasthulu', 1988, 'B.Bhaskara Rao', 'Ilaiyaraaja', 'Rajendra Prasad, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aasthulu-Anthasthulu-1988jpegsensongsmp3.png'),
('Aata', 2007, 'V.N.Aditya', 'Devi Sri Prasad', 'Siddarth, Ileana', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Aata-jpeg-saensongsmp3.jpg'),
('Aata Arambam', 2013, 'Vishnu Vardhan', 'Yuvan Shankar Raja', 'Ajith Kumar,Arya,Rana Daggubati,Nayantara,Tapsee Pannu', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Aata-Arrambam-Telugu-mp3-Songs.jpg'),
('Aata Bommalu', 1966, NULL, 'SP Kodandapani', 'S V Ranga Rao, Kanta Rao', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aata-Bommalu-1966jpeg.jpg'),
('Aataadista', 2008, 'Ravikumar Chowdary', 'Chakri', 'Nitin, Kajal Aggarwal', 'https://sensongsmp3.live/wp-content/uploads/2015/04/aatadistha-songs-download-nithin-kajal-agarwal.jpg'),
('Aatadukundham Raa', NULL, 'Nageswara Reddy G', 'Anup Rubens', 'Sushanth, Sonam Bajwa And Brahmanadam', 'https://sensongsmp3.live/wp-content/uploads/2016/07/Aatadukundham-Raa-songs-sensongsmp3.jpg'),
('Aatagadu', 1980, 'Rama Rao Tatineni', 'K.Chakravarthy', 'N T Rama Rao, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aatagadu-1980jpegsensongsmp3.jpg'),
('Aatagallu', 2018, 'Paruchuri Murali', 'Sai Kartheek', 'Nara Rohit, Darshana Banik, Jagapathi Babu', 'https://sensongsmp3.live/wp-content/uploads/2018/07/aatagallu-2018-telugu-movie-songs-.jpg'),
('Aathma Bandhuvu', 1962, 'P.S. Ramakrishna Rao', 'K.V.Mahadevan', 'N T Rama Rao, Savitri', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aathma-Bandhuvu-1962jpegsensongs-mp3.jpg'),
('Aathmabalam', 1985, 'Tatineni Prasad', 'K Chakravarthy', 'Balakrishna, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aathmabalam-1985jpeg.jpg'),
('Aathmeeyudu', 1977, 'Tatineni Rama Rao', 'J V Raghavulu', 'Akkineni Nageswara Rao, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aathmeeyudu-1977jpeg.jpg'),
('Aathmeeyulu', 1969, 'V.Madhusudhan Rao', 'Saluri Rajeswara Rao', 'Akkineni Nageshwara Rao, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aathmeeyulu-1969jpegsensongsmp3.jpg'),
('Aatma Bandham', 1991, 'Sunil Varma', 'M.M.Keeravani', 'Suman, Lizi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aatma-Bandham-1991jpegsensongsmp3.jpg'),
('Aatma Gowravam', 1965, 'K.Viswanath', 'Saluri Rajeswara Rao', 'Akkineni Nageswara Rao, Kanchana', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aatma-Gowravam-1965jpegsensongsmp3.jpg'),
('Aavesam', 2015, 'Sanjay Leela Bhansali', 'Anirudh Ravi Chander', 'Ajith, Shruti Haasan, Lakshmi Menon', 'https://sensongsmp3.live/wp-content/uploads/2016/11/aavesam-songs-sensongsmp3.jpg'),
('Aavida Maa Aavide', 1998, 'E.V.V.Satyanarayana', 'Sri Kommineni', 'Nagarjuna, Tabu', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aavida-Maa-Aavide-songs.jpeg'),
('Aavu Puli Madhyalo Prabahas Pelli', 2016, 'Nagaram Suneel', 'Madhumani Naidu', 'A.Ravi Teja, Aswini Chandra Sekhar', 'https://sensongsmp3.live/wp-content/uploads/2017/04/Aavu-Puli-Madhyalo-Prabahas-Pelli-2016jpegsensongsmp3.jpg'),
('Aay', 2024, 'Anji Kanchipalii', 'Ram Miriyala', 'Narne Nithin, Nayan Sarika', 'https://sensongsmp3.live/wp-content/uploads/2024/03/Aay-2024.jpg'),
('Aayanaki Iddaru', 1995, 'E.V.V.Satya Narayana', 'Koti', 'Jagapathi Babu, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aayanaki-Iddaru-1995jpegsensongs-mp3.jpg'),
('Aayane Maa Aayana', 1996, 'M.Kalngiyam', 'Ilaiyaraaja', 'Murali, Devayani', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aayane-Maa-Aayana-1996jpegsensongsmp3.jpg'),
('Aayudham', 1990, 'K Murali Mohan Rao', 'K Chakravarthy', 'Krishna, Raadha, Ramesh Babu', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aayudham-1990jpeg.jpg'),
('Abbai Gari Pelli', 1997, 'Sarath', 'Koti', 'Suman, Simran', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Abbai-Gari-Pelli-1997jpegsensongsmp3.jpg'),
('Abbaigaru', 1993, 'E.V.V.Satyanarayana', 'M.M.Keeravani', 'Venkatesh, Meena', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Abbaigaru-1993jpegsensongsmp3.jpg'),
('Abbayi Class Ammayi Mass', 2013, 'Koneti Sreenu', 'Sekar Chandra', 'Varun Sandesh,Haripriya', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Abbai-Class-Ammai-Mass-Telugu-mp3-Songs.jpg'),
('Abbayigaru Ammayigaru', 1972, 'V Ramachandra Rao', 'K V Mahadevan', 'Krishna, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Abbayigaru-Ammayigaru-1972jpeg.jpg'),
('Abbayitho Ammayi', 2015, 'Ramesh Varma', 'Iiaiyaraja', 'Naga Shourya,Palak Lalwani', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Abbayitho-Ammayi-sensongsmp3.jpg'),
('Abhi', 2004, 'Dr.Kiran', 'Devi Sri Prasad', 'Kamalakar, Sonali Joshi', 'https://sensongsmp3.live/wp-content/uploads/2017/02/abhi-jpeg-sensongs-mp3.jpg'),
('Abhilasha', 1983, 'A.Kodandarami Reddy', 'Ilaiyaraaja', 'Chiranjeevi, Radhika', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Abhilasha-1983jpegsensongsmp3.jpg'),
('Abhimaanavathi', 1975, 'Doondee', 'K Chakravarthy', 'Krishna, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Abhimaanavathi-1975jpeg.jpg'),
('Abhimanam', 1960, 'C.S.Rao', 'Ghantasala', 'Akkineni Nageswara Rao, Savithri', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Abhimanam-1960jpegsensongs-mp3.jpg'),
('Abhimanavantulu', 1973, 'K S Rami Reddy', 'SP Kodandapani', 'Krishnam Raju, Saradha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Abhimanavantulu-1973jpeg.jpg'),
('Abhimanyudu', 2018, 'P.S Mithran', 'Yuvan Shankar Raja', 'Vishal, Samantha & Arjun', 'https://sensongsmp3.live/wp-content/uploads/2018/05/abhimanyudu-2018-songs-vishal-samantha.jpeg'),
('Abhinandana', 1988, 'Ashok Kumar', 'Ilaiyaraaja', 'Karthik, Sobhana', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Abhinandana-1988jpegsensongsmp3.jpg'),
('Abhinetri 2016', 2016, 'Vijay', 'Sajid-Wajid', NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/09/abhinetri-mp3-sensongsmp3.jpg'),
('Abhisaarika', 1991, 'Dasari Narayana Rao', 'Vasu Rao', 'Suresh, Vaniviswanath', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Abhisaarika-1991jpeg.jpg'),
('Abhishekam', 1998, 'S V Krishna Reddy', 'S V Krishna Reddy', 'S V Krishna Reddy, Rachana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Abhishekam-1998jpeg.jpg'),
('Achari America Yatra', 2017, 'G Nageswara Reddy', 'Achu Rajamani', 'Manchu Vishnu, Brahmanandam', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Achari-America-Yatra-2018-telugu-movie-songs-posters-images-album-cd-cover-manchu-vishnu-pragya-.jpg'),
('Acharya', 2022, 'Koratala Siva', 'Mani Sharma', 'Chiranjeevi, Kajal Aggarwal, Ram Charan Tej, Pooja Hegde', 'https://sensongsmp3.live/wp-content/uploads/2022/05/Acharya-2022-movie-songs-download.jpeg'),
('Action 3D', 2013, 'Anil Sunkara', 'Bappa Lahiri, Thaman.S, Bappi Lahari', 'Allari Naresh, Snehaullal,Shaam', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Action-3d-Telugu-mp3-Songs.jpg'),
('Adavi', 2009, 'Ram Gopal Varma', 'Imran Bapi Tutul', 'Nithin, Priyanka Kothari', 'https://sensongsmp3.live/wp-content/uploads/2017/02/adavi-jpeg-sensongs-mp3.jpg'),
('Adavi Chukka', 2000, 'Dasari Narayana Rao', 'Vandematarm Srinivas', 'Vijaya Shanti, Charan Raj', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Adavi-Chukka-jpeg-sensongs-mp3.jpg'),
('Adavi Donga', 1985, 'K.Raghavendra Rao', 'Chakravarthy', 'Chiranjeevi, Radha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Adavi-Donga-1985jpegsensongsmp3.jpg'),
('Adavi Raja', 1986, 'K Murali Mohan Rao', 'Chakravarthy', 'Sobhan Babu, Raadha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adavi-Raja-1986jpeg.jpg'),
('Adavi Ramudu', 1977, 'K.Raghavendra Rao', 'K.V.Mahadevan', 'N T Rama Rao, Jayasudha, Jayaprada', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Adavi-Ramudu-1977jpegsensongs-mp3.jpg'),
('Adavi Ramudu 2004', 2004, NULL, 'Mani Sharma', 'Prabhas, Aarti Agarwal', 'https://sensongsmp3.live/wp-content/uploads/2016/10/adavi-raamudu-songs-sensongsmp3.jpg'),
('Adavi Simhalu', 1983, 'K.Raghavendra Rao', 'Chakravarthy', 'Krishna, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Adavi-Simhalu-1983jpegsensongsmp3.jpg'),
('Adavi Veerulu', 1971, 'Subramanyam', 'K V Mahadevan', 'Kanta Rao, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adavi-Veerulu-1971jpeg.jpg'),
('Adavilo Anna', 1997, 'B.Gopal', 'Vandemataram Srinivas', 'Mohan Babu, Roja', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Adavilo-Anna-1997jpegsensongsmp3.jpg'),
('Adbhutham', 2000, 'Saran', 'Bharadwaj', 'Ajith Kumar, Shalini', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Adbhutham-jpeg-sensongs-mp3.jpg'),
('Adda', 2013, 'G.Karthik Reddy', 'Anup Rubens', 'Susanth,Shanvi Srivastava', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Adda-Telugu-mp3-Songs.jpg'),
('Addalameda', 1981, 'Dasari Narayana Rao', 'Rajan Nagendra', 'Murali Mohan, Geetha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Addalameda-1981jpeg.jpg'),
('Ade Nuvvu Ade Nenu', 2009, 'Srinivas', 'Mohan Sithara', 'Shashank, Arya Menon', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Ade-Nuvvu-Ade-Nenu-2009-jpeg-sensongs-mp3.jpg'),
('Adhinayakudu', 2012, NULL, NULL, NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/12/Adhinayakudu-Telugu-mp3-Songs.jpg'),
('Adhipathi', 2001, 'Ravi Raja Pinisetty', 'Saluri Koteswara Rao', 'Mohan Babu, Nagarjuna, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Adhipathi-2001-songs.jpeg'),
('Adhirindhi Alludu', 1996, 'E V V Satyanarayana', 'MM Keeravani', 'Mohan Babu, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adhirindhi-Alludu-1996jpeg.jpg'),
('Adhirindhi Guru', 1997, 'Sagar', 'Koti', 'Krishna, Prema', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adhirindhi-Guru-1997jpeg.jpg'),
('Adhugo', 2018, 'Ravi Babu', 'Prashanth Vihari', 'Abhishek Varma, Nabha Natesh, Ravi Babu, Proorna', 'https://sensongsmp3.live/wp-content/uploads/2018/09/Adugo-2018-telugu-movie-songs-poorna-ravi-babu.jpg'),
('Adhurs', 2010, 'V V Vinayak', 'Devi Sri Prasad', 'Jr NTR, Nayanatara & Sheela', 'https://sensongsmp3.live/wp-content/uploads/2016/09/adhurs-sensongsmp3.jpg'),
('Adi Nuvve', 2010, 'Veera Prasad Neelam', 'Jeevan Thomas', 'Chaitanya, Aksha', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Adhi-Nuvve-Telugu-mp3-Songs.jpg'),
('Adipurush', 2023, 'Om Raut', 'Ankit Balhara, Sanchit Balhara, Ajay Gogavale, Atul Gogavale', 'Prabhas, Kriti Sanon, Saif Ali Khan, Sunny Singh', 'https://sensongsmp3.live/wp-content/uploads/2023/05/Adipurush-songs-download-2023-telugu-prabhash.jpg'),
('Adirindhi', 2017, 'Atlee', 'A. R. Rahman', 'Vijay, Samantha, Kajal Aggarwal & Nithya Menen', 'https://sensongsmp3.live/wp-content/uploads/2017/10/Adirindji-2017-telugu-movie-songs-vijaykajal-aggarwalsamanthanithya-menona-r-rahaman.jpg'),
('Aditya 369', 1991, 'Singeetam Srinivasa Rao', 'Ilaiyaraaja', 'Balakrishna, Mohini', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aditya-369-1991jpeg.jpg'),
('Adrushta Jatakudu', 1974, 'K Hemambaradara Rao', 'T Chalapathi Rao', 'N T Rama Rao, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adrushta-Jatakudu-1974jpeg.jpg'),
('Adrushtam', 1992, 'Mouli', 'Anand Milind', 'Naresh, Yamuna', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adrushtam-1992jpeg.jpg'),
('Adrustavanthulu', 1969, 'V Madhusudhan Rao', 'K V Mahadevan', 'Akkineni Nageswara Rao, Jayalalitha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adrustavanthulu-1969jpeg.jpg'),
('Adugu', 2009, NULL, 'Jeevan Thomas', 'Samarendra, Reecha Soni', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Adugu-2009jpeg.jpg'),
('Adugu Jaadalu', 1966, 'Tapi Chanakya', 'Master Venu', 'N T Rama Rao, Saroja Devi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Adugu-Jaadalu-1966jpegsensongsmp3.jpg'),
('Agent', 2023, 'Surendar Reddy', 'Hip Hop Thamizha', 'Akhil Akkineni, Mammotty, Sakshi Vaidya', 'https://sensongsmp3.live/wp-content/uploads/2023/03/Agent-2023-Telugu-Mp3-Songs-Download-Akhil-Akkineni-Mammotty-Sakshi-Vaidya-Hip-Ho-Tamizha.jpg'),
('Agent Bairavaa', 2017, 'Bharathan', 'Santhosh Narayanan', 'Vijay, Keerthy Suresh', 'https://sensongsmp3.live/wp-content/uploads/2017/08/Agent-Bairavaa-2017-Telugu-songs.jpg'),
('Agent Gopi', 1978, 'K.S.R.Das', 'Sathyam', 'Krishna, Jayaprada', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Agent-Gopi-1978jpegsensongsmp3.jpg'),
('Agent Vikram', 1985, NULL, 'Ilaiyaraaja', 'Kamal Hassan, Viji, Dimple Kapadia', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Agent-Vikram-1985jpeg.jpg'),
('Aggi Barata', 1966, 'B.Vitthalacharya', 'Vijaya Krishnamurthy', 'N T Rama Rao, Rajasree', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aggi-Barata-1966jpegsensongsmp3.jpg'),
('Aggi Dora', 1967, 'B.Vitthalacharya', 'Vijaya Krishnamurthy', 'Kanta Rao, Rajasree', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aggi-Dora-1967jpegsensongs-mp3.jpg'),
('Aggi Meeda Guggilam', 1968, 'G Viswanatham', 'Satyam', 'Kanta Rao, Rajasree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aggi-Meeda-Guggilam-1968jpeg.jpg'),
('Aggi Pidugu', 1964, 'B.Bitthalacharya', 'Rajen Nagendra', 'N T Rama Rao, Krishna Kumari', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Aggi-Pidugu-1964jpegsensongs-mp3.jpg'),
('Aggi Ramudu', 1954, 'S.M. Sri Ramulu Naidu', 'Subbayya Naidu', 'N T Rama Rao, Bhanumathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aggi-Ramudu-1954jpeg.jpg'),
('Aggi Ravva', 1981, 'K Bapaiah', 'K V Mahadevan', 'N T Rama Rao, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aggi-Ravva-1981jpeg.jpg'),
('Aggi Ravvalu', 1997, 'Gulzar', 'Vishal Bhardwaj', 'Tabu, Om Puri, Chandrachur Singh, Jimmy Shergill', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aggi-Ravvalu-1997jpeg.jpg'),
('Aggi Veerudu', 1969, 'B.V.Srinivas', 'Vijaya Krishnamoorthy', 'N T Rama Rao, Rajasree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aggi-Veerudu-1969jpeg.jpg'),
('Agni', 1989, 'K. Raghavendra Rao', 'Hamsalekha', 'Nagarjuna, Shantipriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Agni-1989jpegsensongsmp3.jpg'),
('Agni Gundam', 1984, 'Kranthi Kumar', 'Chakravarthy', 'Chiranjeevi, Sumalatha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Agni-Gundam-1984jpegsensongsmp3.jpg'),
('Agni Keratalu', 1988, 'Tatineni Rama Rao', 'K.Chakravarthy', 'Krishna, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Agni-Keratalu-1988jpegsensongsmp3.jpeg'),
('Agni Paravatham', 1985, 'K.Raghavendra Rao', 'K.Chakravarthy', 'Krishna, Vijaya Shanthi, Radha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Agni-Paravatham-1985jpegsensongsmp3.jpg'),
('Agni Pareeksha', 1970, 'Varaprasad Rao', 'P. Adinarayana Rao', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Agni-Pareeksha-1970jpeg.png'),
('Agni Poolu', 1981, 'K Bapaiah', 'K V Mahadevan', 'Krishnam Raju, Jayasudha, Jayapradha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Agni-Poolu-1981jpeg.png'),
('Agni Putrudu', 1987, 'Raghavendra Rao', 'Chakravarthy', 'Nagarjuna, Nageswara Rao, Rajani', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Agni-Putrudu-songs.jpeg'),
('Agni Samadhi', 1983, 'K S R Das', 'Satyam', 'Naresh, Poornima', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Agni-Samadhi-1983jpeg.jpg'),
('Agni Samskaram', 1979, 'G V Prabhakar', 'Janardhan', 'Chiranjeevi, Madhavi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Agni-Samskaram-1979jpeg.jpg'),
('Agnyaathavaasi', 2018, 'Trivikram Srinivas', 'Anirudh Ravichander', 'Pawan Kalyan, Keerthy Suresh & Anu Emmanuel', 'https://sensongsmp3.live/wp-content/uploads/2018/01/Agnyaathavaasi-songs.jpeg'),
('Aha Naa Pellanta', 1987, 'Jandhyala', 'Ramesh Naidu', 'Rajendra Prasad, Rajani', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aha-Naa-Pellanta-1987jpeg.jpg'),
('Ahankaari', 1992, 'Dasari Narayana Rao', 'Raj Koti', 'Rajasekhar, Sobhana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ahankaari-1992jpeg.jpg'),
('Ahimsa', 2023, 'Teja', 'RP Patnaik', 'Abhiram Daggubati, Geethika Tiwary', 'https://sensongsmp3.live/wp-content/uploads/2023/06/Ahimsa-2023-telugu-movie-songs.jpg'),
('Aho Brahma Oho Sishya', 1997, NULL, 'Saasi Preetam', 'Shivaji Raja, Rakshita', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aho-Brahma-Oho-Sishya-1997jpeg.png'),
('Ajay', 1996, 'K.Bhagyaraja', 'Anand Milind', 'Nagarjuna, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ajay-1996jpeg.jpg'),
('Akasa Veedhilo', 2001, 'Singeetham Srinivasa Rao', 'M.M.Keeravani', 'Nagarjuna, Raveena Tondon', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Akasa-Veedhilo-songs.jpeg'),
('Akbar Saleem Anarkali', 1978, 'N T Rama Rao', 'C.Ramchandra', 'N T Rama Rao, Balakrishna, Deepa', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Akbar-Saleem-Anarkali-1978jpegsensongsmp3.jpg'),
('Akhanda', 2021, 'Boyapati Srinu', 'S S Thaman', 'Balakrishna, Srikanth, Poorna, Pragya Jaiswal', 'https://sensongsmp3.live/wp-content/uploads/2021/11/Akhanda-Songs-Download-Balakrishna-Srikanth-Poorna-Pragya-Jaiswal.jpeg'),
('Akhanda 2', 2025, 'Boyapati Srinu', 'S. Thaman', 'Balakrishna, Samyuktha Menon', 'https://sensongsmp3.live/wp-content/uploads/2025/06/Akhanda-2-2025-298x180.jpg'),
('Akhandudu', 1970, 'V.Ramchanra rao', 'T Chalapathi Rao', 'Krishna, Mukkamala', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Akhandudu-1970jpegsensongsmp3.jpg'),
('Akhil', 2015, 'V.V.Vinayak', 'S.S Thaman', 'Akhil, Sayyeshaa Saigal', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Akhil-2015-telugu-mp3-sensongsmp3.jpg'),
('Akka Chellelu', 1957, NULL, 'Pendyala Nageswara Rao', 'Amarnath, Sri Ranjani', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Akka-Chellelu-1957jpeg.png'),
('Akka Mogudu', 1992, 'Kranti Kumar', 'Koti', 'Rajasekhar, Suhasini', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Akka-Mogudu-1992jpeg.jpg'),
('Akka Thammudu', 1972, 'R Krishnan', 'K V Mahadevan', 'A.V.M.Rajan. Jayalalitha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Akka-Thammudu-1972jpeg.jpg'),
('Akkada Abbayi Ikkada Ammayi', 1996, NULL, 'Koti', 'Pawan Kalyan & Supriya', 'https://sensongsmp3.live/wp-content/uploads/2016/08/akkada-ammayi-ikkada-abbayi-mp3-sensongsmp3.jpg'),
('Akkada Ammayi Ikkada Abbayi', 2025, 'Nitin – Bharath', 'Radhan', 'Pradeep Machiraju, Deepika Pilli', 'https://sensongsmp3.live/wp-content/uploads/2024/12/Akkada-Ammayi-Ikkada-Abbayi-2024.jpg'),
('Akkum Bakkum', 1996, 'Srinivas Reddy', 'Vidyasagar', 'Ali, Babu Mohan', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Akkum-Bakkum-1996jpeg.jpg'),
('Ala', 2018, 'Sarat Palanki', 'Srinivasa Sarma Rani', 'Bhargav Kommera, Shilpika, Malavika', 'https://sensongsmp3.live/wp-content/uploads/2018/07/Ala-2018-telugu-movie-songs-download.jpg'),
('Ala Aithe', 2012, 'Vijay Morpala', 'Sai Karthik', 'Vijay Dharan, Hemanthini', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Ala-Aithe-Telugu-mp3-Songs.jpg'),
('Ala Ela', 2014, 'Aneesh Krishna', 'Bheems', 'Rahul Ravindran, Hebah Patel', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Ala-Ela-Telugu-mp3-Songs.jpg'),
('Ala Vaikuntapuramlo', 2020, 'Trivikram Srinivas', 'S S Thaman', 'Allu Arjun, Pooja Hegde, Nivetha Pethuraj', 'https://sensongsmp3.live/wp-content/uploads/2019/12/ala-vaikuntapuramlo-songs-download-2020.jpg'),
('Alaa Modalaindi', 2010, 'B.V.Nandini Reddy', 'Kalyani Malik', 'Nani, Nithya Menon', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Alaa-Modalaindi-Telugu-mp3-Songs.jpg'),
('Alalu', 2010, 'Sunil Bandi', 'Sai Karthik', 'Suresh, Vijay Sai, Roopa', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alalu-2010jpeg.jpg'),
('Alcohol', 2026, 'Meher Tej', 'Ghibran', 'Allari Naresh, Ruhani Sharma', 'https://sensongsmp3.live/wp-content/uploads/2025/11/Alcohol-movie-songs-298x180.jpg'),
('Alexander', 1992, 'K Ranga Rao', 'Raj Koti', 'Suman, Vani Viswanath', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alexander-1992jpeg.jpg'),
('Alias Janaki', NULL, NULL, NULL, NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/11/Alias-Janaki-Telugu-mp3-Songs.jpg'),
('Alibaba 40 Dongalu', 1970, 'B.Vitthalacharya', 'Ghantasala', 'N T Rama Rao, Jayalalitha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Alibaba-40-Dongalu-1970jpegsensongsmp3.jpg'),
('Alibaba Adbutha Deepam', 1995, 'Sathya', 'Vidya Sagar', 'Ali, Yuvarani', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Alibaba-Adbutha-Deepam-1995-songs-download-sensongsmp3co.jpg'),
('Alibaba Aradozen Dongalu', 1994, 'E V V Satyanarayana', 'Vidyasagar', 'Rajendra Prasad, Ravali', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alibaba-Aradozen-Dongalu-1994jpeg.jpg'),
('Alibaba Intlo Andharu Dhongalu', 2011, 'Neelan K Sekhar', 'Vidyasagar', 'Krishna, Janani', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alibaba-Intlo-Andharu-Dhongalu-2011jpeg.jpg'),
('All Rounder', 1998, 'Prabhakar', 'Veena Paani', 'Rajendra Prasad, Sanghavi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/All-Rounder-1998jpegsensongsmp3.jpg'),
('All The Best', 2012, NULL, NULL, NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/12/All-The-Best-Telugu-mp3-Songs.jpg'),
('Allari', 2002, 'Ravi Babu', 'Paul J', 'Allari Naresh, Swetha Agarwal', 'https://sensongsmp3.live/wp-content/uploads/2017/02/allari-jpeg-sensongs-mp3.jpg'),
('Allari Baava', 1980, 'Sambasiva Rao', 'Rajan Nagendra', 'Krishna, Jayapradha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Baava-1980jpeg.jpg'),
('Allari Bullodu', 1978, 'G.C.Sekhar', 'K.Chakravarthy', 'Krishna, Jayaprada', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Allari-Bullodu-1978jpegsensongsmp3.jpg'),
('Allari Donga', 1993, 'Parthiban', 'Ilaiyaraaja', 'Parthiban, Aishwarya', 'https://sensongsmp3.live/wp-content/uploads/2015/05/allari-donga-1993-songs-sensongsmp3co.png'),
('Allari Krishnayya', 1986, 'Nandamuri Ramesh', 'Chakravarthy', 'Balakrishna, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Krishnayya-1986jpeg.jpg'),
('Allari Mogudu', 1992, 'K Raghavendra Rao', 'M. M. Keeravani', 'Mohan Babu, Ramya Krishna, Meena', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Mogudu-1992jpeg.jpg'),
('Allari Pidugu', 2005, 'Jayanth C Panarje', 'Mani Sharma', 'Balakrishna, Katrina Kaif', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Allari-Pidugu-jpeg-sensongs-mp3.jpg'),
('Allari Pilla', 1992, 'Kodi Ramakrishna', 'Vidyasagar', 'Suresh, Meena', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Pilla-1992jpeg.jpg'),
('Allari Pilla Anumaanapu Pellam', 1999, 'Ramesh Kanna', 'Ilaiyaraaja', 'Ajith, Devayani, Heera', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Pilla-Anumaanapu-Pellam-1999jpeg.jpg'),
('Allari Pillalu', 1979, NULL, 'Satyam', 'Ramakrishna, Jayachitra', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Pillalu-1979jpeg.jpg'),
('Allari Police', 1994, 'Uppalapati Narayana Rao', 'Ilaiyaraaja', 'Mohan Babu, Amani', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Allari-Police-1994jpegsensongsmp3.jpg'),
('Allari Prema', 1996, NULL, 'Ilaiyaraaja', 'Prasanth, Subhashri', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Prema-1996jpeg.jpg'),
('Allari Premikudu', 1994, 'K.Raghavendra Rao', 'M.M.Keeravani', 'Jagapathi Babu, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Allari-Premikudu-1994jpegsensongsmp3-1.jpg'),
('Allari Priyudu', 1993, 'K.Raghavendra Rao', 'M.M.Keeravani', 'Rajasekhar, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Allari-Donga-1993jpegsensongsmp3.jpg'),
('Allari Ramudu', 2002, 'B Gopal', 'R P Patnaik', NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/09/allari-ramudu-sensongsmp3.jpg'),
('Allari Vayasu', 1979, 'Rajasekhar', 'J V Raghavulu', 'Murali Mohan, Jayachitra', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allari-Vayasu-1979jpeg.jpg'),
('Allarodu', 1994, 'K Ajay Kumar', 'Vidyasagar', 'Rajendra Prasad, Surabhi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allarodu-1994jpeg.jpg'),
('Allauddin Adbhutha Deepam', 1957, 'T.R.Raghunath', 'Saluri Rajeswara Rao', 'Akkineni Nageswara Rao, Anjali Devi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allauddin-Adbhutha-Deepam-1957jpeg.jpg'),
('Alluda Mazaaka', 1995, 'E.V.V.Satyanarayana', 'Koti', 'Chiranjeevi, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Alluda-Mazaaka-1995-jpegsensongsmp3.jpg'),
('Allude Menalludu', 1970, 'V Madhusudhan Rao', 'B Shankar', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allude-Menalludu-1970jpeg.png'),
('Alludochchaadu', 1976, NULL, 'T Chalapathi Rao', 'Ramakrishna, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alludochchaadu-1976jpeg.jpg'),
('Alludu Adhurs', 2021, 'Santosh Srinivas', 'Devi Sri Prasad', 'Bellamkonda Sai Srinivas, Nabha Natesh, Anu Emmanuel & Prakash Raj', 'https://sensongsmp3.live/wp-content/uploads/2020/02/alludu-adhurs-2021-telugu-movie-songs-download-bellam-konda-sai-srinivas-nabha-natash.jpg'),
('Alludu Dhidhina Kapuram', 1991, 'Krishna', 'Chakravarthy', 'Krishna, Sobhana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alludu-Dhidhina-Kapuram-1991jpeg.jpg'),
('Alludu Kosam', 1987, 'M.S.Kota Reddy', 'Satyam', 'Chandra Mohan, Kalpana', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Alludu-Kosam-1987jpegsensongs-mp3.jpg'),
('Alludu Pattina Bharatham', 1980, 'K Viswanath', 'K Chakravarthy', 'Krishnam Raju, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alludu-Pattina-Bharatham-1980jpeg.jpg'),
('Alludu Seenu', 2014, 'V.V.Vinayak', 'Devi Sri Prasad', 'Bellamkonda Sreenivas, Samantha', 'https://sensongsmp3.live/wp-content/uploads/2015/04/alludu-seenu-songs.jpg'),
('Alludu Singam', 2017, 'Rajasekhar', 'N.R.Raghunanthan', 'Vimal, Anjali', 'https://sensongsmp3.live/wp-content/uploads/2017/11/Alludu-singam-2017-telugu-movie-songs-download.jpg'),
('Alludugaru', 1990, 'K.Raghavendra Rao', 'K.V.Mahadevan', 'Mohan Babu, Shobana', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Alludugaru-1990jpegsensongsmp3.jpg'),
('Alludugaru Vacharu', 1999, 'Ravi Raja Pinisetty', 'M. M. Keeravani', 'Jagapathi Babu, Heera, Kousalya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alludugaru-Vacharu-1999jpeg.jpg'),
('Alludugaru Zindabad', 1981, 'Katta Subba Rao', 'Chakravarthy', 'Sobhan Babu, Saradha, Geetha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Alludugaru-Zindabad-1981jpeg.jpg'),
('Allullosthunnaru', 1983, NULL, 'Chakravarthy', 'Chiranjeevi, Chandra Mohan, Geetha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Allullosthunnaru-1983jpeg.jpg'),
('Alluri Seetharama Raju', 1974, 'V.Ramachandra Rao', 'P. Adinarayana Rao', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Alluri-Seetharama-Raju-1974jpegsensongsmp3.jpg'),
('Amaayakuraalu', 1971, 'V Madhusudhan Rao', 'Saluri Rajeswara Rao', 'Akkineni Nageswara Rao, Saradha, Kanchana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amaayakuraalu-1971jpeg.jpg'),
('Amar Akbar Anthony', 2018, 'Srinu Vaitla', 'S S Thaman', 'Ravi Teja, Ileana D’Cruz ,Sunil, Laya', 'https://sensongsmp3.live/wp-content/uploads/2018/11/amar-akbar-anthony-songs.jpeg'),
('Amara Geetham', 1982, NULL, 'Ilaiyaraaja', 'Mohan, Poornima', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amara-Geetham-1982jpeg.jpg'),
('Amara Jeevi', 1983, 'Jandhyala', 'Chakravarthy', 'Akkineni Nageswara Rao, Jayapradha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amara-Jeevi-1983jpeg.jpg'),
('Amara Prema', 1978, 'Tatineni Rama Rao', 'K Chakravarthy', 'Kamal Hassan, Zarina Wahab', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amara-Prema-1978jpeg.jpg'),
('Amara Sandesham', 1954, 'Adhurthi Subbarao', NULL, 'Sri Ranjani, Amarnath', 'https://sensongsmp3.live/wp-content/uploads/2015/12/Amara-Sandesham-1954-songs.jpg'),
('Amara Silpi Jakkana', 1964, 'B.S.Ranga', 'S. Rajeswara Rao', 'Akkineni Nageswara Rao, Saroja Devi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amara-Silpi-Jakkana-1964jpegsensongsmp3.jpg'),
('Amaradeepam', 1977, 'K.Raghavendra Rao', 'Sathyam', 'Krishnam Raju, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amaradeepam-1977jpegsensongsmp3.jpg'),
('Amavasya Chandrudu', 1981, 'Singeetam Srinivasa Rao', 'Ilaiyaraaja', 'Kamal Hassan, Madhavi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amavasya-Chandrudu-1981jpeg.jpg'),
('Amayakudu', 1968, 'Addala Narayana rao', 'Ravi Shankar', 'Krishna, Jamuna', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amayakudu-1968jpegsensongsmp3.jpg'),
('Ameerpeta lo', 2016, NULL, 'Murali Leon', 'Srikanth and Ashwini', 'https://sensongsmp3.live/wp-content/uploads/2016/07/ameerpetalo-telugu-movie-posters-images-songs-sensongsmp3.jpg'),
('America Abbayi', 1987, 'Singeetam Srinivasa Rao', 'Saluri Rajeswara Rao', 'Rajasekhar, Raadhika', 'https://sensongsmp3.live/wp-content/uploads/2017/12/America-Abbayi-1987jpeg.jpg'),
('America Alludu', 1985, 'K Vasu', 'Chakravarthy', 'Suman, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/America-Alludu-1985jpeg.jpg'),
('America Ammayi', 1976, 'Singeetam Srinivasa Rao', 'G. K. Venkatesh', 'Ranganath, Sridhar', 'https://sensongsmp3.live/wp-content/uploads/2015/12/America-Ammayi-1976-songs.jpg'),
('Ami Thumi', 2017, 'Indraganti Mohanakrishna', 'Mani Sharma', 'Eesha Rebba, Aditi Myakal, Adivi Sesh, Srinivas Avasarala', 'https://sensongsmp3.live/wp-content/uploads/2017/02/ami-thumi-songs-sensongsmp3co.jpg'),
('Amigos', 2023, 'Rajendra Reddy', 'Ghibran', 'Kalyan Ram, Ashika Ranganathan', 'https://sensongsmp3.live/wp-content/uploads/2023/02/amigos-2023-telugu-songs-download.jpg'),
('Amma', 2013, NULL, 'Raghuram', NULL, 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-2013jpeg.jpg'),
('Amma Cheppindi', 2006, 'Gangaraju Gunnam', 'M.M.Keeravani', 'Sharwanand, Shriya Reddy', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Amma-Cheppindi-2006jpeg-sensongs-mp3.jpg'),
('Amma Donga', 1995, 'Sagar', 'Koti', 'Krishna, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amma-Donga-1995jpegsensongsmp3.jpg'),
('Amma Evarikaina Amma', 1979, 'R Thyagarajan', 'Ilaiyaraaja', 'Rajinikanth, Mohan Babu, Sripriya', 'https://sensongsmp3.live/wp-content/uploads/2015/12/Amma-Evarikaina-Amma-1979-songs-rajinikanth.jpg'),
('Amma Koduku', 1993, 'Kranthi Kumar', 'Ilaiyaraaja', 'Rajasekhar, Sukanya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amma-Koduku-1993jpegsensongsmp3.jpg'),
('Amma Kosam', 1970, 'K Pratyagatma', 'P. Adinarayana Rao', 'Krishna, Rekha, Krishnam Raju', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-Kosam-1970jpeg.jpg'),
('Amma Leni Puttillu', 1995, 'Sai Pratap', 'Vandemataram Srinivas', 'Ooha, Sashi Kumar', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-Leni-Puttillu-1995jpeg.jpg'),
('Amma Manasu', 1974, 'K Viswanath', 'K V Mahadevan', 'Chalam, Jayanthi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-Manasu-1974jpeg.jpg'),
('Amma Mata', 1972, 'V Ramachandra Rao', 'Ramesh Naidu', 'Sobhan Babu, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-Mata-1972jpeg.jpg'),
('Amma Naa Kodalaa!', 1997, 'Sagar', NULL, 'Vinod Kumar, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2015/12/Amma-Naa-Kodalaa-1997-songs.jpg'),
('Amma Nanna O Tamila Ammayee', 2003, 'Puri Jagannadh', 'Chakri', 'Ravi Teja & Asin', 'https://sensongsmp3.live/wp-content/uploads/2016/09/amma-naanna-o-tamilammayi-sensongsmp3.jpg'),
('Amma Nannu Deevinchu', 1984, NULL, 'Ilaiyaraaja', 'Siva Kumar, Sujatha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Amma-Nannu-Deevinchu-1984jpeg.jpg'),
('Amma Rajinama', 1991, 'Dasari Narayana Rao', 'K.Chakravarthy', 'Dasri Narayana Rao, Sharada', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Amma-Rajinama-1991jpegsensongs-mp3.jpg'),
('Ammaa Nanna', 1976, 'T Lenin Babu', 'T Chalapathi Rao', 'Krishnam Raju, Jayasudha, Prabha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ammaa-Nanna-jpeg.jpg'),
('Ammailu Abbailu', 2003, 'Ravi Babu', 'Chakri', 'Vijay, Vidya', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Ammailu-Abbailu-2003jpeg-sensongs-mp3.jpg'),
('Ammammagarillu', 2018, 'Sundhar', 'Kalyana Ramana', 'Naga Shourya, Shamili', 'https://sensongsmp3.live/wp-content/uploads/2017/03/AmmaGariIllu-2018-telugu-movie-songs-download-naga-shourya-shalini.jpg'),
('Ammayi Bagundi', 2004, 'Balasekharan', 'M.M.Srilekha', 'Sivaji, Meera Jasmine', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Ammayi-Bagundi-2004jpeg-sensongs-mp3.jpg'),
('Ammayi Kapuram', 1994, 'Muthyala Subbayya', 'Vandemataram Srinivas', 'Anand, Ali, Maheswari', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ammayi-Kapuram-1994jpeg.jpg'),
('Ammayi Pelli', 1974, NULL, 'Bhanumathi Ramakrishna', 'N T Rama Rao, Bhanumathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ammayi-Pelli-1974jpeg.jpg'),
('Amurutha Varsham', 2006, 'N.Chandrasekhar', 'Kalyani Malik', 'Sameer Dattani, Ramya', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Amrutha-Varsham-jpeg-sensongs-mp3.jpg'),
('Anaarkali', 2012, 'P.N.Roy', 'K.Vidya Pratap', 'Omkar Gowri Sharma', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Anarkali-Telugu-mp3-Songs.jpg'),
('Anaganaga O Ammayi', 1999, 'Ramesh Sarangan', 'Mani Sharma', 'Srikanth, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anaganaga-O-Ammayi-1999jpegsensongsmp3.jpg'),
('Anaganaga O Dheerudu', 2011, 'Prakash Kovelamudi', 'M.M.Keeravani, Koti', 'Siddarth, Shruti Haasan', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Anaganaga_Oka_Dheerudu-Telugu-mp3-Songs.jpg'),
('Anaganaga O Premakatha', 2018, 'Pratap Tatamsetti', 'KC Anjan', 'Ashwin J Viraj, Riddhi Kumar', 'https://sensongsmp3.live/wp-content/uploads/2018/09/Anaganaga-O-Premakatha-Songs-Download.jpg'),
('Anaganaga Oka Aranyam', 2009, 'Sekhar Chandra', 'T.Sultan', 'Kaushal, Sairabhanu', 'https://sensongsmp3.live/wp-content/uploads/2017/02/anaganaga-oka-aranyam-jpeg-sensongs-mp3.jpg'),
('Anaganaga Oka Chitram', 2015, 'J.Prabhakar Reddy', 'Vinod Yajamanya', 'Siva, Megasri', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Anaganaga-Oka-Chitram-songs-sensongsmp3.jpg'),
('Anaganaga Oka Raju', 2026, 'Maari', 'Mickey J Meyer', 'Naveen Polishetty, Meenakshi Chaudhary', 'https://sensongsmp3.live/wp-content/uploads/2025/09/Anaganaga-Oka-Raju-2025-Songs-298x180.jpg'),
('Anaganaga Oka Roju', 1997, 'Ram Gopal Varma', 'Sri Kommineni', 'J.D.Chakravarthy, Urmila Matondkar', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anaganaga-Oka-Roju-1997jpegsensongsmp3.jpg'),
('Anamika', 2014, 'Sekhar Kammula', 'MM Keeravani', 'Nayanthara , Vaibhav, Pasupathy, Harshvardhan, Sri Ranjini', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Anamika-Telugu-mp3-Songs.png'),
('Anand', 2004, 'Sekhar Kammula', 'K. M. Radha Krishnan', 'Raja, Kamalini Mukherjee', 'https://sensongsmp3.live/wp-content/uploads/2021/08/Anand-Telugu-Movie-Songs-Download.jpeg'),
('Ananda Bhairavi', 1984, 'Jandhyala', 'Ramesh Naidu', 'Harish, Malavika Sarkar', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Ananda-Bhairavi-1984jpegsensongsmp3.jpg'),
('Anandam', 2001, 'Srinu Vaitla', 'Devi Sri Prasad', 'Aakash, Rekha', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Anandam-jpeg-sensongs-mp3.jpg'),
('Ananthapuram 1980', 2009, 'M.Sasikumar', 'James Vasanthan', 'Jai, Swathy Reddy', 'https://sensongsmp3.live/wp-content/uploads/2017/02/ananthapuram-jpeg-sensongs-mp3.jpg'),
('Anarkali', 1955, 'Vedantam Raghavaiah', 'P. Adinarayana Rao', 'Akkineni Nageswara Rao, Anjali Devi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anarkali-1955jpegsensongsmp3.jpg'),
('Anasuyamma Gari Alludu', 1986, 'A.Kodandarami Reddy', 'K.Chakravarthy', 'Balakrishna, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anasuyamma-Gari-Alludu-1986jpegsensongsmp3.jpg'),
('Andadu Aagadu', 1979, NULL, 'Satyam', 'Krishnam Raju, Latha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andadu-Aagadu-1979jpeg.jpg'),
('Andagadu', 1981, NULL, 'Ilaiyaraaja', 'Kamal Hassan, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andagadu-1981jpeg.png'),
('Andala Raasi', 1980, NULL, 'Ramesh Naidu', 'Rajkumar, Rati', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andala-Raasi-1980jpeg.jpg'),
('Andala Rakshasi', 2012, 'Hanu Raghavapudi', 'Radhan', 'Naveenchandra, Rahul Ravindran, Lavanya Tripathi', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Andala-Rakshasi-Telugu-mp3-Songs.jpg'),
('Andala Ramudu', 1973, 'Bapu', 'K.V.Mahadevan', 'Akkineni Nageswara Rao, Latha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Andala-Ramudu-1973jpegsensongsmp3.jpg'),
('Andamaina Manasulo', 2007, NULL, 'R.P.Patnaik', 'Rajeev, Ramya', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Andamaina-Manasulo-jpeg-sensongs-mp3.jpg'),
('Andaman Ammayi', 1979, 'V Madhusudhan Rao', 'K V Mahadevan', 'Akkineni Nageswara Rao, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andaman-Ammayi-1979jpeg.jpg'),
('Andari Bandhuvaya', 2010, 'Chandra Siddartha', 'Anoop Rubense', 'Sharvanand, Padma Priya', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Andari-Bandhuvaya-Telugu-mp3-Songs.jpg'),
('Andariki Monagadu', 1971, 'Mallikarjuna Rao', 'Satyam', 'Krishna, Bharathi, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andariki-Monagadu-1971jpeg.png'),
('Andarivaadu', 2005, 'Srinu Vaitla', 'Devi Sri Prasad', 'Chiranjeevi, Tabu, Rakshitha, Rimi Sen', 'https://sensongsmp3.live/wp-content/uploads/2017/11/Andarivaadu-2000-Telugu-movie-songs-chiranjeevi.jpg'),
('Andaru Dongale', 1974, 'V B Rajendra Prasad', 'K V Mahadevan', 'Sobhan Babu, Lakshmi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andaru-Dongale-1974jpeg.jpg'),
('Andham Kosam Pandhem', 1971, NULL, 'SP Kodandapani', 'Kanta Rao, Kanchana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andham-Kosam-Pandhem-1971jpeg.jpg'),
('Andhamaina Abaddham', 2008, 'Ravi Raja Pinishetty', 'Srilekha', 'Raja, Kamna Jethmalani', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Andhamaina-Abaddham-2008jpeg-sensongs-mp3.jpg'),
('Andharikante Monagaadu', 1986, 'T Krishna', 'K V Mahadevan', 'Krishna, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2015/12/Andharikante-Monagaadu-1986-songs.jpg'),
('Andharu Manchivaare', 1975, 'S S Balan', 'V. Kumar', 'Sobhan Babu, Manjula', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andharu-Manchivaare-1975jpeg.jpg'),
('Andhhagadu', 2017, NULL, 'Sekhar Chandra', 'Raj Tarun, Hebah Patel', 'https://sensongsmp3.live/wp-content/uploads/2017/06/andhagadu-songs-download-Raj-Tarun-Hebah-Patel-2017.jpg'),
('Andhra Kesari', 1983, 'Vijay Chander', 'Satyam', 'Murali Mohan, Harish', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Andhra-Kesari-1983jpeg.jpg'),
('Andhra King Taluka', 2025, 'P. Mahesh Babu', 'Vivek – Mervin', 'Ram Pothineni, Bhagya Shri Borse, Upendra', 'https://sensongsmp3.live/wp-content/uploads/2025/03/Andhra-King-Teluka-2025-Songs-298x180.jpg'),
('Andhra Pori', 2015, 'Raj Madiraj', 'Dr.J. Rajasekhara Varma', 'Mastar Akash Puri, Ulka Guptha', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Andhra-Pori-songs-sensongsmp3.jpg'),
('Andhrawala', 2004, NULL, 'Chakri', NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/09/andrawala-sensongsmp3.jpg'),
('Andhrudu', 2005, 'Paruchuri Murali', 'Kalyani Malik', 'Gopichand, Gowri Pandit', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Andhrudu-songs.jpg'),
('Anekudu', 2015, 'K.V.Anand', 'Harris Jayaraj', 'Dhanush, Amyra Dastur', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Anekudu-songs-sensongsmp3.jpg'),
('Anga Rakshakudu', 1994, NULL, 'M. M. Keeravani', 'Rajasekhar, Meena', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anga-Rakshakudu-1994jpeg.jpg'),
('Angel', 2017, 'Palani', 'Bheems Ceciroleo', 'Naga Anvesh, Hebah Patel', 'https://sensongsmp3.live/wp-content/uploads/2017/05/angel-2017-telugu-movie.jpg'),
('Anjali', 1990, 'Mani Ratnam', 'Ilaiyaraaja', 'Revathi, Prabhu', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anjali-1990jpegsensongsmp3.jpg'),
('Anjali CBI', 2019, 'R Ajay Gnanamuthu', 'HipHop Tamizha', 'Nayanthara, Atharvaa Murali, Anurag Kashyap, Raashi Khanna', 'https://sensongsmp3.live/wp-content/uploads/2019/02/anjali-cbi-songs-downloa-nayanatara-raashi-khanna.jpg'),
('Anjaneyulu 2009', 2009, NULL, 'S S Thaman', 'Ravi Teja & Nayanatara', 'https://sensongsmp3.live/wp-content/uploads/2016/09/anjaneyulu-sensongsmp3.jpg'),
('Anjani Puthrudu', 2009, 'K.Chandrasekharan', 'Vandematarm Srinivas', 'Nagendra Babu, Ramya Krishna', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Anjani-Puthrudu-2009jpeg-sensongs-mp3.jpg'),
('Anji', 2003, 'Kodi Ramakrishna', 'Mani Sharma', 'Chiranjeevi, Namrata Shirodkar', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Anji-2003jpeg-sensongs-mp3.jpg'),
('Ankuram', 1992, 'C Umamaheswara Rao', 'Hamsalekha', 'Sarath Babu, Revathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ankuram-1992jpeg.jpg'),
('Ankusam', 1990, 'Kodi Ramakrishna', 'K Chakravarthy', 'Rakasekhar, Jeevitha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ankusam-1990jpeg.jpg'),
('Ankusham', 2008, 'Saravana Sakthi', 'Mariya Manohar', 'J.R.Rithesh, Sangeetha', 'https://sensongsmp3.live/wp-content/uploads/2017/02/ankusham-jpeg-sensongs-mp3.jpg'),
('Anna', 1994, 'Muthyala Subbaiah', 'M. M. Keeravani', 'Rajasekhar, Gauthami, Roja', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anna-1994jpeg.jpg'),
('Anna Chellelu', 1960, 'B Vittalacharya', 'Rajan Nagendra', 'Chalam, Devika', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anna-Chellelu-1960jpeg.jpg'),
('Anna Thammudu', 1990, 'Koti', 'Raj Koti', 'Krishna, Gowthami', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anna-Thammudu-1990jpeg.jpg'),
('Annadammula Anubandham', 1975, 'S.D.Lall', 'K.Chakravarthy', 'N T Rama Rao, Latha', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Annadammula-Anubandham-1975jpegsensongsmp3.jpg'),
('Annadammula Saval', 1978, 'K S R Das', 'Satyam', 'Krishna, Rajinikanth, Chandrakala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Annadammula-Saval-1978jpeg.jpg'),
('Annadhammulu', 1969, NULL, 'K V Mahadevan', 'Krishna, Jamuna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Annadhammulu-1969jpeg.jpg'),
('Annamayya', 1997, 'K.Ragavendra Rao', 'M.M.Keeravani', 'Akkineni Nagarjuna, Ramya Krishna, Suman', 'https://sensongsmp3.live/wp-content/uploads/2015/04/annamayya-songs.jpg'),
('Annapoorna', 1960, NULL, 'Susarla Dakshinamurthy', 'Jaggayya, Jamuna', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Annapoorna-1960jpeg.jpg'),
('Annavaram', 2006, NULL, 'Ramana Gogula', 'Pawan Kalyan, Asin & Sandhya', 'https://sensongsmp3.live/wp-content/uploads/2016/08/annavaram-mp3-sensongsmp3.jpg'),
('Annayya', 2000, 'J. Venkateshwara Rao', 'Mani Sharma', 'Chiranjeevi, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2015/04/annayya-songs-download.jpg'),
('Anta Mana Manchike', 1972, 'Bhanumathi', 'Bhanumathi Satyam', 'Krishna, Bhanumathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anta-Mana-Manchike-1972jpeg.jpg'),
('Antariksham', 2019, 'Sankalp Reddy', 'Prashanth R Vihari', 'Varun Tej, Lavanya Tripathi & Aditi Rao Hydari', 'https://sensongsmp3.live/wp-content/uploads/2018/12/Antariksham-songs-download-varun-tej-lavanya-tripati-songs.jpg'),
('Ante Sundaraniki', 2022, 'Vivek Athreya', 'Vivek Sagar', 'Nani, Nazriya Fahadh', 'https://sensongsmp3.live/wp-content/uploads/2022/06/ante-sundaraniki-songs.jpeg'),
('Anthaka Mundu Aa Tarvatha', 2013, 'Mohan Krishna Indraganti', 'Kalyan Malik', 'Sumanth Ashwin,Eesha', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Anthaku-Mundu-Aa-Tharuvatha.jpg'),
('Anthaku Minchi', 2018, 'Jhony', 'Suneel Kashyap', 'Jai, Rashmi Gautam', 'https://sensongsmp3.live/wp-content/uploads/2018/08/Anthaku-Minchi-2018-Telugu-Movie-Songs-Download-Rashmi-Gowtham-Postes-images-cd-cover.jpg'),
('Antham', 1992, 'Ram Gopal Varma', 'Mani Sharma', 'Nagarjuna, Urmila Matondkar', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Antham-1992-songs.jpeg'),
('Antham Kadidi Aarambam', 1981, 'Vijaya Nirmala', 'Ramesh Naidu', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Antham-Kadidi-Aarambam-1981jpegsensongsmp3.jpg'),
('Anthapuram', 1998, 'Krishna Vamsy', 'Ilaiyaraaja', 'Jagapathi Babu, Soundarya, Saikumar', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anthapuram-1998jpeg.png'),
('Anthasthulu', 1965, 'V.Madhusudhan Rao', 'K.V.Mahadevan', 'Akkineni Nageswara Rao, Krishna Kumari', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Antastulu-1965jpegsensongsmp3.jpg'),
('Anthuleni Katha', 1976, 'K.Balachander', 'M. S. Viswanathan', 'Kamal Haasan, Jayaprada', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anthuleni-Katha-1976jpegsensongsmp3.jpg'),
('Anubandhalu', 1991, 'Jayachitra', 'Ilaiyaraaja', 'Rehman, Rupini', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anubandhalu-1991jpeg.jpg'),
('Anubandham', 1984, 'A.Kodandarami Reddy', 'Chakravarthy', 'Akkineni Nageswara Rao, Raadhika', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anubandham-1984jpegsensongsmp3.jpg'),
('Anukunnadi Sadhistha', 1979, 'P Chandrasekhar Reddy', 'Ramesh Naidu', 'Nagesh', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anukunnadi-Sadhistha-1979jpeg.jpg'),
('Anuraagam', 1961, 'G Ramineedu', 'Pendyala Nageswara Rao', 'Bhanumathi, Varalakshmi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anuraagam-1961jpeg.jpg'),
('Anuradha', 1971, 'P Chandrasekhar Reddy', 'K V Mahadevan', 'Krishna, Vijaya Nirmala, Krishnam Raju', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anuradha-1971jpeg.jpg'),
('Anuraga Bandham', 1985, 'Anil Kumar', 'Rajan Nagendra', 'Sarath Babu, Jayasudha, Saritha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anuraga-Bandham-1985jpeg.jpg'),
('Anuraga Devatha', 1982, 'Tatineni Rama Rao', 'K.Chakravarthy', 'N T Rama Rao, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anuraga-Devatha-1982jpegsensongsmp3.jpg'),
('Anuraga Sangamam', 1986, 'Maniratnam', 'Ilaiyaraaja', 'Mohan, Raadha, Ambika', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anuraga-Sangamam-1986jpeg.jpg'),
('Anuragalu', 1975, 'K S Rami Reddy', 'Satyam', 'Nagabhsanam, Sridevi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Anuragalu-1975jpeg.jpg'),
('Anveshana', 1985, 'Vamsy', 'Ilaiyaraaja', 'Karthik, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Anveshana-1985jpegsensongsmp3.jpg'),
('Apadbhandavudu', 1992, 'K Viswanath', 'M. M. Keeravani', 'Chiranjeevi, Meenakshi Seshadri', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Apadbhandavudu-1992jpeg.jpg'),
('Aparichithudu', 2005, 'S.Shankar', 'Harris Jayaraj', 'Vikram, Sadha', 'https://sensongsmp3.live/wp-content/uploads/2017/02/aparichitudu-jpeg-sensongs-mp3.jpg'),
('Apartment', 2011, NULL, NULL, 'Nikitha', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Apartment-Telugu-mp3-Songs.jpg'),
('Apoorva Sahodarulu', 1986, 'K Raghavendra Rao', 'Chakravarthy', 'Balakrishna, Vijaya Shanthi, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Apoorva-Sahodarulu-1986jpeg.jpg'),
('Appatlo Okadundevadu', NULL, 'Sagar K Chandra', 'Sai Karthik', NULL, 'https://sensongsmp3.live/wp-content/uploads/2016/11/appatlo-okadundevadu-mp3-sensongsmp3.jpg'),
('Appu Chesi Pappu Kudu', 1959, 'L.V.Prasad', 'Saluri Rajeswara Rao', 'N.T. Rama Rao, Savithri', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Appu-Chesi-Pappu-Kudu-1959-songs-sensongsmp3co.jpg'),
('Appudo Ippudo Eppudo', 2024, 'Sudheer Varma', 'Karthik', 'Nikhil, Rukmini Vasanth', 'https://sensongsmp3.live/wp-content/uploads/2024/10/Appudo-Ippudo-Eppudo-2024.jpg'),
('Appula Appa Rao', 1991, 'E V V Satyanarayana', 'Rajan Nagendra', 'Rajendra Prasad, Sobhana', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Appula-Appa-Rao-1991jpeg.jpg'),
('April Okati Vidudala', 1991, 'Vamsy', 'Ilaiyaraaja', 'Rajendra Prasad, Shobana', 'https://sensongsmp3.live/wp-content/uploads/2017/04/April-Okati-Vidudala-1991jpegsensongsmp3.jpg'),
('Apuroopam', 2003, 'G.S.Ravi Kumar', 'Chakri', 'Priyanka Chopra, Prasanna', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Apuroopam-2003jpeg-sensongs-mp3.jpg'),
('Araku Road Lo', NULL, 'Vasudev', 'Raahul Raj, Waasudev', 'Sri Sai Shankar, Nikisha Patel', 'https://sensongsmp3.live/wp-content/uploads/2016/07/araku-road-lo-sensongsmp3.jpg'),
('Aranya Kanda', 1987, 'Kranthi Kumar', 'K.Chakravarthy', 'Nagarjuna, Ashwini', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aranya-Kanda-songs.jpeg'),
('Aranyam', 1996, 'Tinu Varma', 'Vijay Varma', 'Arjun Sarja, Biyanka Desai', 'https://sensongsmp3.live/wp-content/uploads/2015/05/aranyam-songs-sensongsmp3co.jpg'),
('Aravinda Sametha', 2018, 'Trivikram Srinivas', 'S S Thaman', 'Jr NTR, Pooja Hegde & Jagapathi Babu, Sunil, Devayani', 'https://sensongsmp3.live/wp-content/uploads/2018/09/Aravindha-Sametha-songs-download-Jr-NTR-Pooja-Hegde.jpeg'),
('Ardhaangi', 1996, NULL, 'M. M. Keeravani', 'Anand, Ravali', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ardhaangi-1996jpeg.jpg'),
('Ardharathri', 1969, 'Sambasiva Rao', 'Master Venu', 'Jaggayya, Bharathi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ardharathri-1969jpeg.png'),
('Ardharatri Swatantram', 1986, 'R.Narayana Murthy', 'Vandemataram Srinivas', 'R. Narayana Murthy, T,Krishna', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Ardharatri-Swatantram-1986-songs-sensongsmp3co.jpg'),
('Ardhashathabdam', 2021, 'Rawindra Pulle', 'Nawfal raja AIS', 'Karthik Rathnam , Navin Chandra,Sai Kumar, Krishna Priya', 'https://sensongsmp3.live/wp-content/uploads/2021/06/Ardhashathabdam-songs-download.jpeg'),
('Arjun 2004', NULL, NULL, 'Mani Sharma', 'Mahesh Babu, Shreya', 'https://sensongsmp3.live/wp-content/uploads/2016/08/mahesh-babu-arjun-sensongsmp3.jpg'),
('Arjun Reddy', 2017, 'Sandeep Vanga', 'Radhan', 'Vijay Deverakonda, Shalini Pandey', 'https://sensongsmp3.live/wp-content/uploads/2017/10/Arjun-Reddy-songs-vijay-devara-konda-shalini-pande-songs.jpeg'),
('Arjun Suravaram', 2019, 'TN Santhosh', 'Sam C S', 'Nikhil Siddharth, Lavanya Tripati', 'https://sensongsmp3.live/wp-content/uploads/2019/03/arjun-suravaram-songs-download.jpg'),
('Arjun s/o Vyjayanthi', 2025, 'Pradeep Chilukuri', 'B. Ajneesh Loknath', 'Kalyan Ram, Vijaya Shanthi, Saiee M Manjrekar', 'https://sensongsmp3.live/wp-content/uploads/2025/03/Arjun-Son-of-Vyjayanthi-2025-298x180.jpg'),
('Arthangi', 1954, 'P Pullaiah', 'Master Venu', 'Akkineni Nageswara Rao, Savithri', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Arthangi-1954jpeg.jpg'),
('Aruna Kiranam', 1986, 'Muthyala Subbaiah', 'Chakravarthy', 'Rajasekhar, Vijaya Shanthi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aruna-Kiranam-1986jpeg.jpg'),
('Arunachalam', 1997, 'Sunder.C', 'Deva', 'Rajinikanth, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2015/08/Arunachalam-songs-download-rajinikanth-soundrya.jpg'),
('Arundhathi', 1997, 'Kranti Kumar', 'M. M. Keeravani', 'Soundarya, Raadhika', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Arundhathi-1997jpeg.jpg'),
('Arya 2', 2009, NULL, 'Devi Sri Prasad', 'Allu Arjun, Kajal Aggarwal, Navadeep', 'https://sensongsmp3.live/wp-content/uploads/2015/03/aarya-2-songs-sensongsmp3co.jpg'),
('Arya Mp3 Songs', NULL, NULL, 'Devi Sri Prasad', 'Allu Arjun, Anuradha Mehata', 'https://sensongsmp3.live/wp-content/uploads/2016/07/arya-mp3-songs-sensongsmp3.jpg'),
('Asaadhyudu', 1968, 'V.Ramachandra Rao', 'T Chalapathi Rao', 'Krishna, K. R.Vijaya', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Asaadhyudu-1968-sensongsmp3o.jpg'),
('Asha Asha Asha', 1995, 'Vasanth', 'Deva', 'Ajith, Suvalakshmi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Asha-Asha-Asha-1995jpegsensongsmp3.jpg'),
('Asha Jyothi', 1981, 'Tatineni Prakash Rao', 'Chakravarthy', 'Murali Mohan, Sujatha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Asha-Jyothi-1981jpeg.jpg'),
('Ashok', 2006, 'Surender Reddy', 'Mani Sharma', 'Jr NTR, Sameera Reddy', 'https://sensongsmp3.live/wp-content/uploads/2016/09/ashok-mp3-songs-sensongsmp3.jpg'),
('Ashoka Chakravarthy', 1989, 'SS Ravichandran', 'Ilaiyaraaja', 'Balakrishna, Bhanupriya', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Ashoka-Chakravarthy-1989jpegsensongsmp3.jpg'),
('Ashoka Vanamlo Arjuna Kalyanam', 2022, 'Vidya Sagar Chinta', 'Jai Krish', 'Vishwak Sen, Rukshar Dhillon, Ritika Nayak', 'https://sensongsmp3.live/wp-content/uploads/2022/05/Ashoka-Vanamlo-Arjuna-Kalyanam-songs.jpeg'),
('Ashtalakshmi Vaibhavam', 1986, 'C S Rao', 'K V Mahadevan', 'Ranganath, K R Vijaya', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ashtalakshmi-Vaibhavam-1986jpeg.jpg'),
('Ashwamedham', 1992, 'K Raghavendra Rao', 'Ilaiyaraaja', 'Balakrishna, Nagma, Meena, Sobhan Babu', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ashwamedham-1992jpeg.jpg'),
('Ashwathama', 2020, 'Ramana Teja', 'Sricharan Pakala', 'Naga Shaurya, Mehreen Pirzada & Sargun Kaur', 'https://sensongsmp3.live/wp-content/uploads/2019/12/Ashwathama-2020-telugu-mvovie-songs-download-naga-shourya-mehreen.jpg'),
('Assembly Rowdy', 1991, 'B.Gopal', 'K.V.Mahadevan', 'Mohan Babu, Divya Bharathi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Assembly-Rowdy-1991jpegsensongsmp3.jpg'),
('Astha Chamma', 2008, 'Mohan Krishna Indraganti', 'Kalyani Malik', 'Nani, Swathi Reddy', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Astha-Chamma-2008jpeg-sensongs-mp3.jpg'),
('Asthram', 2006, 'Suresh Krishna', 'S.A.Rajkumar', 'Manchu Vishnu, Anushka Shetty', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Asthram-2006wiki.jpg'),
('Asura', 2015, 'Krishna Vijay', 'Sai Karthik', 'Nara Rohit, Priya Banerjee', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Asura-songs-download-sensongsmp3.jpg'),
('Atha Mechina Alludu', 1989, 'Kodi Ramakrishna', 'K V Mahadevan', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Atha-Mechina-Alludu-1989jpeg.jpg'),
('Athade', 2012, NULL, 'Rajamani', 'Akash, Keerthi Chawla', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athade-2012jpeg.jpg'),
('Athade Oka Sainyam', 2004, NULL, 'S.V.Krishna Reddy', 'Jagapathi Babu, Neha', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Athade_Oka_Sainyam-jpeg-sensongs-mp3.jpg'),
('Athadu Mp3 Songs', NULL, NULL, 'Mani Sharma', 'Mahesh babu, Trisha', 'https://sensongsmp3.live/wp-content/uploads/2016/07/athadu-sensongsmp3.jpg'),
('Athagaru Kotha Kodalu', 1968, NULL, 'G. K. Venkatesh', 'Krishna, Vijaya Nirmala', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athagaru-Kotha-Kodalu-1968jpeg.jpg'),
('Athaku Koduku Mamaku Alludu', 1993, 'PN Ramachandra Rao', 'Chakravarthy', 'Vinod Kumar, Roja, Divya Vani', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athaku-Koduku-Mamaku-Alludu-1993jpeg.jpg'),
('Athalu Kodallu', 1971, 'P Chandrasekhar Reddy', 'K V Mahadevan', 'Krishna, Vanisree', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athalu-Kodallu-1971jpeg.jpg'),
('Athani Kante Ghanudu', 1978, 'G.C.Sekhar', 'K.Chakravarthy', 'Krishna, Jayaprada', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Athani-Kante-Ghanudu-songs-sensongsmp3co.jpg'),
('Athanokkade', 2005, 'Surender Reddy', 'Mani Sharma', 'Kalyan Ram, Sindu Tolani', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Athanokkade-2005-jpeg-sensongs-mp3.jpg'),
('Athidhi', 2007, NULL, 'Mani Sharma', 'Mahesh Babu & Amrita Rao', 'https://sensongsmp3.live/wp-content/uploads/2016/09/athidhi-sensongsmp3.jpg'),
('Athinti Kapuram', 1952, NULL, NULL, NULL, 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athinti-Kapuram-1952jpeg.png'),
('Athintlo Adde Mogudu', 1991, 'Relangi Narasimha Rao', 'M. M. Keeravani', 'Rajendra Prasad, Nirosha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Athintlo-Adde-Mogudu-1991jpeg.jpg'),
('Aththa Kodallu', 1994, 'Sarath', 'Raj Koti', 'Rajkumar, Vijaya Shanthi', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aththa-Kodallu-1994jpeg.jpg'),
('Atithi Devobhava', 2022, 'Polimera Nageshwar', 'Sekhar Chandra', 'Aadi Saikumar, Nuveksha', 'https://sensongsmp3.live/wp-content/uploads/2021/10/Atithi-Devo-Bhava-Songs-download-2021.jpeg'),
('Atta Okinti Kodale', 1958, 'K B Tilak', 'Pendyala Nageswara Rao', 'Jaggayya, Girija', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Atta-Okinti-Kodale-1958jpeg.jpg'),
('Attack', 2016, 'Ram Gopal Varma', 'Ravi Shankar', 'Manchu Manoj, Surabhi', 'https://sensongsmp3.live/wp-content/uploads/2017/04/Attack-2016jpegsensongsmp3.jpg'),
('Attagari Pettanam', 1981, 'Raja Chandra', 'Satyam', 'Murali Mohan, Saritha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Attagari-Pettanam-1981jpeg.jpg'),
('Attagaru Swagatham', 1988, 'Kodi Ramakrishna', 'K V Mahadevan', 'Kalyan Chakravarthy, Ashwini', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Attagaru-Swagatham-1988jpeg.jpg'),
('Attarintiki Daredi', 2013, NULL, 'Devi Sri Prasad', 'Pawan Kalyan, Samantha & Pranitha', 'https://sensongsmp3.live/wp-content/uploads/2015/05/Attarintiki-Daredi-mp3-songs-posters-images-sensongsmp3co.jpg'),
('Atthaki Yamudu Ammayiki Mogudu', 1989, 'A.Kodandarami Reddy', 'K.Chakravarthy', 'Chiranjeevi, Vijaya Shanthi', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Atthaki-Yamudu-Ammayiki-Mogudu-1989jpegsensongsmp3.jpg'),
('Atthanu Diddhina Kodalu', 1972, 'S. Narayan', 'Master Venu', 'Haranath, Jamuna', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Atthanu-Diddhina-Kodalu-1972jpeg.jpg'),
('Atu Itu Kaani Hrudayam Thoti', 2016, 'JK.G Chowdary', 'G.P.Raviin', 'Jagadeesh, Lipi', 'https://sensongsmp3.live/wp-content/uploads/2017/04/Atu-Itu-Kaani-Hrudayam-Thoti-2016jpegsensongsmp3.jpg'),
('Aunty', 1990, 'Mouli', 'Ramesh Vinayagam', 'Nassar, Jayasudha', 'https://sensongsmp3.live/wp-content/uploads/2017/12/Aunty-1990jpeg.jpg'),
('Aunty Uncle Nandagopal', 2010, 'DVK Nageswara Rao', 'Vandemataram Srinivas', 'Vadde Naveen, Lakshana', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Aunty-Uncle-Nandagopal-Telugu-mp3-Songs.jpg'),
('Auto Driver', 1998, 'Suresh Krishna', 'Deva', 'Nagarjuna, Simran, Deepti Bhatnagar', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Auto-Driver-nagarjuna.jpeg'),
('Autonagar Surya', 2014, 'Deva Katta', 'Anup Rubens', 'Naga Chaitanya, Samantha', 'https://sensongsmp3.live/wp-content/uploads/2015/03/auto-nagar-surya-songs-download-naga-chaitanya-samantha.jpg'),
('Avakai Biryani', 2008, 'Anish Kuruvilla', 'Manikanth Kadri', 'Kamal Kamaraju, Bindu Madhavi', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Avakai-Biryani-2008jpeg-sensongs-mp3.jpg'),
('Avathaarudu', 2008, 'S.S.Selva', 'Srikanth Deva', 'Ajith, Asin', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Avathaarudu-2008-jpeg-sensongs-mp3.jpg'),
('Avatharam', 2014, 'Siby K. Thomas, Udaykrishnan', 'Deepak Dev', 'Madhavan Mahadevan, Manimeghala', 'https://sensongsmp3.live/wp-content/uploads/2016/11/Avatharam-Telugu-mp3-Songs.jpg'),
('Ave Kallu', 1967, 'A.C.Trilogchander', 'Veda', 'Krishna, Kanchana', 'https://sensongsmp3.live/wp-content/uploads/2017/03/Ave-Kallu-1967jpegsensongsmp3.jpg'),
('Avunanna Kadanna', 2005, 'Teja', 'R.P.Patnaik', 'Uday Kiran, Sada', 'https://sensongsmp3.live/wp-content/uploads/2017/02/Avunanna-Kadanna-2005jpeg-sensongs-mp3.jpg'),
('Avunu Validdaru Ishtapaddaru', 2002, 'Vamsy', 'Chakri', 'Ravi Teja & Kalyani', 'https://sensongsmp3.live/wp-content/uploads/2016/09/avunu-validharu-istapadaru-mp3-sensongsmp3.jpg'),
('Awaara', 2010, 'N.Lingu Swamy', 'Yuvan Shankar Raja', 'Karthi, Tamanna', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Awaara-Telugu-2013-songs-.jpg'),
('Awe', 2018, 'Prashanth Varma', 'Mark K Robin', 'Kajal Aggarwal, Nithya Menen, Regina Cassandra, Eesha Rebba, Srinivas Avasarala, Priyadarshi Pulikonda, Murali Sharma, Rohini Molleti', 'https://sensongsmp3.live/wp-content/uploads/2018/02/awe-2018-songs.jpeg'),
('Ayyappa Swami Janma Rahasyam', 1987, NULL, 'K V Mahadevan', NULL, 'https://sensongsmp3.live/wp-content/uploads/2017/12/Ayyappa-Swami-Janma-Rahasyam-1987jpeg.jpg'),
('Ayyare', 2011, 'Sagar Chandra', 'Sunil Kasyap', 'Shivaji, Rajendra Prasad, Anisha Singh', 'https://sensongsmp3.live/wp-content/uploads/2016/12/Ayyare-Telugu-mp3-Songs.jpg'),
('Azad', 2000, 'Thirupathisamy', 'Mani Sharma', 'Nagarjuna, Soundarya', 'https://sensongsmp3.live/wp-content/uploads/2015/04/Aazaad-Songs-download.jpeg'),
('Kotha Kodalu', 1970, 'Hemambaradararao', 'Sathyam', 'Chandra Mohan, Rojaramani', 'https://sensongsmp3.live/wp-content/uploads/2015/08/Kotha-Kodalu-1970.jpg');

