-- Albums INSERT statements
-- Generated from Pagal World scraper

INSERT IGNORE INTO albums (
    title, language, description, thumbnail_url, year,
    director, music_director, star_cast, created_at, updated_at
) VALUES
(
    'K.J. Yesudas Sings For Mgr',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3182042/3182042.jpg',
    2020,
    NULL,
    'Various Artists',
    NULL,
    NOW(),
    NOW()
),
(
    'Kaadhal Theevey (From Dharala Prabhu)',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182023/3182023.jpg',
    2020,
    '',
    'Sean Roldan',
    '',
    NOW(),
    NOW()
),
(
    'Kadhalukku',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182025/3182025.jpg',
    2020,
    '',
    'Sharan, Jasper',
    '',
    NOW(),
    NOW()
),
(
    'Kandhapuranam Vol   2',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182021/3182021.jpg',
    2020,
    '',
    'Thiru Muruga Kirubananda Variyar',
    '',
    NOW(),
    NOW()
),
(
    'Kandhapuranam Vol   3',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182020/3182020.jpg',
    2020,
    '',
    'Thiru Muruga Kirubananda Variyar',
    '',
    NOW(),
    NOW()
),
(
    'Kandhapuranam Vol   4',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182019/3182019.jpg',
    2020,
    '',
    'Thiru Muruga Kirubananda Variyar',
    '',
    NOW(),
    NOW()
),
(
    'Kandhapuranam Vol   5',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182018/3182018.jpg',
    2020,
    '',
    'Thiru Muruga Kirubananda Variyar',
    '',
    NOW(),
    NOW()
),
(
    'Kandhapuranam Vol   6',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182017/3182017.jpg',
    2020,
    '',
    'Thiru Muruga Kirubananda Variyar',
    '',
    NOW(),
    NOW()
),
(
    'Kannum Kannum',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182022/3182022.jpg',
    2020,
    '',
    'Harris Jayaraj',
    '',
    NOW(),
    NOW()
),
(
    'Karuppankaatu Valasu',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182026/3182026.jpg',
    2020,
    '',
    'Adithyha Soorya',
    '',
    NOW(),
    NOW()
),
(
    'Kodambakkam',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3182054/3182054.jpg',
    2004,
    NULL,
    'Sirpy',
    NULL,
    NOW(),
    NOW()
),
(
    'Konchi Pesalama',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3182048/3182048.jpg',
    2006,
    NULL,
    'Ilaiyaraaja',
    NULL,
    NOW(),
    NOW()
),
(
    'Kung Superstar (From Kung Kutta 2)',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3182024/3182024.jpg',
    2020,
    '',
    'Razor Ray',
    '',
    NOW(),
    NOW()
),
(
    'L R Eswari Cine Classics Hits',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3181990/3181990.jpg',
    2003,
    NULL,
    'L. R. Eswari',
    NULL,
    NOW(),
    NOW()
),
(
    'L. Ramesh Cine Jewels On Guitar',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3181984/3181984.jpg',
    2001,
    NULL,
    'L. Ramesh',
    NULL,
    NOW(),
    NOW()
),
(
    'L.R.Eswari Ivvalavuthan Ulagam Vol 2',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3181972/3181972.jpg',
    1996,
    NULL,
    'L. R. Eswari',
    NULL,
    NOW(),
    NOW()
),
(
    'L.R.Eswari Paarvai Ondre Pothume Hits',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3181979/3181979.jpg',
    1995,
    NULL,
    'L. R. Eswari',
    NULL,
    NOW(),
    NOW()
),
(
    'Leelai',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3182016/3182016.jpg',
    2009,
    NULL,
    'Satish Chakravarthy',
    NULL,
    NOW(),
    NOW()
),
(
    'Letus Worship',
    'tamil',
    '',
    'https://pagalworldmusic.com/downloads/cover/3182010/3182010.jpg',
    2003,
    NULL,
    'Angeline Jacob, Jane Jacob, Pastor Jacob, Jason Jacob, Bhushan Dua',
    NULL,
    NOW(),
    NOW()
),
(
    'Life Of Jesus (Vol. 2)',
    'tamil',
    '1 tracks',
    'https://pagalworldmusic.com/downloads/cover/3181991/3181991.jpg',
    2003,
    '',
    'Bhushan Dua',
    '',
    NOW(),
    NOW()
);

