-- Singers INSERT statements
-- Generated from scraping data with data cleanup

INSERT IGNORE INTO singers (singer_name) VALUES
('Aditi Bhavaraju'),
('Adviteeya Vojjala'),
('Ajay Atul'),
('Anandi Joshi'),
('Anirudh Ravichander'),
('Anjana Soumya'),
('Anuraag Kulkarni'),
('Anurag Kulkarni'),
('Aparna'),
('Arjun Chandy'),
('Armaan Malik'),
('Arun Kaundinya'),
('Aruna Sairam'),
('Balakrishna'),
('Benny Dayal'),
('Bheems Ceciroleo'),
('Blazee'),
('Brijesh Shandiliya'),
('Chaitra'),
('Chakri'),
('Chitra'),
('Daler Mehendi'),
('Deepak Blue'),
('Deepthi Parthasaradhy'),
('Deepu'),
('Deepu & Usha'),
('Devi Sri Prasad'),
('Dhanunjay'),
('Dhee'),
('Dhinakar'),
('Dinker'),
('Divija Karthic'),
('Divya Kumar'),
('GV Prakash Kumar'),
('Ganga & Udit Narayana'),
('Geetha Madhuri'),
('Gotte Kanakavva'),
('Hari Haran'),
('Haricharan'),
('Hariharan'),
('Harika Narayan'),
('Harini'),
('Harini Ivvaturi'),
('Harish Sivaramakrishna'),
('HemaChandra'),
('Hiphop Tamizha'),
('Indravathi Chauhan'),
('Jaspreet Jasz'),
('Javed Ali'),
('Jessi Gist'),
('KK'),
('Kaala Bhairava'),
('Kailash Kher'),
('Karthik'),
('Karthik & Vardhani Thaman'),
('Karuna'),
('Karunya'),
('Kausalya'),
('Keerthana Vaidyanathan'),
('Ks Chitra & Jessi Gift'),
('Lipsika'),
('M L Shruti'),
('ML Shruti'),
('Maalathi'),
('Mahalakshmi'),
('Mahati Swara Sagar'),
('Mallikarjuna & Sunitha'),
('Mallikarjuna Rao'),
('Maneesha'),
('Mangli'),
('Manisha Eerabathini'),
('Mano'),
('Mano & Gango'),
('Mano & R P Patnaik & Usha'),
('Masnisha errabathini'),
('Megha Sravanthi'),
('Mohana'),
('Mohana Bhogaraju'),
('N C Karunya'),
('NTR & Rita'),
('Nakash Aziz'),
('Narendra'),
('Naresh Iyer'),
('Naveen & Jyotsna'),
('Naveen Madhav & Rita'),
('Nikitha Srivalli'),
('Niranjana Ramanan'),
('Padmalatha'),
('Parampara Tandon'),
('Pawan Kalyan'),
('Penchal Das'),
('Poojan Kohli'),
('Prashanth R Vihari'),
('Priya Hamesh & Baba Sehgal'),
('Priya sisters'),
('R P Patnaik & Usha'),
('Raajulakey Raraju'),
('Rabbit Mac'),
('Radhika & Murali'),
('Raghu Kunche'),
('Raghuram'),
('Rahul Nambiar'),
('Rahul Nambiar & Dharmana'),
('Rahul Nambiar & Naveen Madhav'),
('Rahul Sipligunj'),
('Ram Miriyala'),
('Ramajogayya Sastry'),
('Ramana Gogula'),
('Ramya Behara'),
('Ramya Behera'),
('Ramya Behra'),
('Ramya Mehra'),
('Ranina Reddy'),
('Ranjith'),
('Ranjith & Anushka Manchanda'),
('Ranjith KG'),
('Ravi Varma'),
('Ravi Varma & Usha'),
('Revanth'),
('Rita & Karthik'),
('Rohit Paritala'),
('Roll Rida'),
('S P Bala Subramanayam & Usha'),
('S P BalaSubramanyam'),
('S P Balasubrahmanyam'),
('S P Balasubramanyam & Gopika Purnima'),
('S P Balu'),
('S P Charan'),
('S. Aishwarya'),
('S. Aishwarya & S. Soundarya'),
('S. Soundarya & Sruthi Ranjani'),
('S. Thaman'),
('S.P.Balu'),
('SP Balasubramanyam & Chitra'),
('SP Charan'),
('Sachet Tandon'),
('Sachin Balu'),
('Sagar & Haripriya'),
('Sahithi Chaganti'),
('Sahiti'),
('Sahiti Chaganti'),
('Sai Charan'),
('Saketh'),
('Saketh Komanduri'),
('Sameera Bharadwaj'),
('Sandhya'),
('Sangeetha'),
('Sanjith Hegde'),
('Sarvepalli Sisters'),
('Satya Yamini'),
('Sekhar'),
('ShakthiSree Gopalan'),
('Shankar Mahadevan'),
('Shankar Mahadevan & Rahul Nambiar'),
('Shreya Ghosal & Kanul Ganjawala'),
('Shreya Ghoshal'),
('Shweta Mohan'),
('Sid Sriram'),
('Siddharth Mahadevan & Shivam Mahadevan'),
('Siddharth Watkins'),
('Simha'),
('Smita'),
('Sonu Nigam'),
('Sooranna'),
('Sravana Bhargavi'),
('Sreya Ghoshal'),
('Sri Krishna'),
('Srikrishna'),
('Srivardhini & Hari Charan'),
('Sruthi Ranjani'),
('Suchitra Karthik Kumar & Mika Singh'),
('Sudhamayi'),
('Sujatha Mohan & Ravi Varma'),
('Sukhwinder Singh'),
('Suriya'),
('Sweekar Agasthi'),
('Swetha Mohan'),
('Tanvi Shah & Devan Ekambaram'),
('Theme –'),
('Tippu'),
('Tippu & Kalyani'),
('Title Song –'),
('Uma Neha'),
('Usha & Karthik'),
('V. M. Mahalingam'),
('Vaishnavi'),
('Various'),
('Vedala Hemachandra'),
('Venky'),
('Vijay Prakash'),
('Vijay Yesudas'),
('Violin Bits –'),
('Yadu Krishnan K'),
('Yamini Ghantasala'),
('Yazin Nizar');

