-- Drop existing tables if they exist (in reverse order of foreign key dependencies)
DROP TABLE IF EXISTS user_playlists CASCADE;
DROP TABLE IF EXISTS singers CASCADE;
DROP TABLE IF EXISTS music_directors CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS user_role CASCADE;

-- Drop existing triggers if they exist
DROP TRIGGER IF EXISTS set_timestamp_users ON users;
DROP TRIGGER IF EXISTS set_timestamp_albums ON albums;
DROP TRIGGER IF EXISTS set_timestamp_songs ON songs;
DROP TRIGGER IF EXISTS set_timestamp_artists ON artists;
DROP TRIGGER IF EXISTS set_timestamp_music_directors ON music_directors;
DROP TRIGGER IF EXISTS set_timestamp_user_playlists ON user_playlists;

-- Drop existing function if it exists
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

CREATE TYPE user_role AS ENUM ('user', 'admin');

-- Shared trigger to keep updated_at aligned with MySQL's ON UPDATE behavior
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(191) NOT NULL,
    email VARCHAR(191) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Albums Table
CREATE TABLE IF NOT EXISTS albums (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) UNIQUE,
        description TEXT,
        thumbnail_id INTEGER,
        thumbnail_url VARCHAR(500),
        year INTEGER,
        director VARCHAR(255),
        music_director VARCHAR(255),
        star_cast TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Songs Table
CREATE TABLE IF NOT EXISTS songs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        album_id BIGINT NOT NULL,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        singer VARCHAR(255),
        thumbnail_id INTEGER,
        thumbnail_url VARCHAR(500),
        audio_id INTEGER,
        audio_url VARCHAR(500),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE
);

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS idx_album_title;
DROP INDEX IF EXISTS idx_song_title;
DROP INDEX IF EXISTS idx_song_album;

-- Create Index for faster queries
CREATE INDEX idx_album_title ON albums(title);
CREATE INDEX idx_song_title ON songs(title);
CREATE INDEX idx_song_album ON songs(album_id);

-- Create Artists Table (many-to-many junction table)
CREATE TABLE IF NOT EXISTS artists (
        artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        artist_name VARCHAR(255) NOT NULL,
        album_id BIGINT NOT NULL,
        album_name VARCHAR(255) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
        CONSTRAINT unique_artist_album UNIQUE (artist_name, album_id)
);

-- Create Singers Table
CREATE TABLE IF NOT EXISTS singers (
        singer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        singer_name VARCHAR(255) NOT NULL,
        UNIQUE (singer_name)
);

-- Create Music Directors Table (many-to-many junction table)
CREATE TABLE IF NOT EXISTS music_directors (
        director_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        director_name VARCHAR(255) NOT NULL,
        album_id BIGINT NOT NULL,
        album_name VARCHAR(255) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
        CONSTRAINT unique_director_album UNIQUE (director_name, album_id)
);

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS idx_artist_album;
DROP INDEX IF EXISTS idx_artist_name;
DROP INDEX IF EXISTS idx_singer_name;
DROP INDEX IF EXISTS idx_director_album;
DROP INDEX IF EXISTS idx_director_name;

-- Create Indexes for faster queries
CREATE INDEX idx_artist_album ON artists(album_id);
CREATE INDEX idx_artist_name ON artists(artist_name);
CREATE INDEX idx_singer_name ON singers(singer_name);
CREATE INDEX idx_director_album ON music_directors(album_id);
CREATE INDEX idx_director_name ON music_directors(director_name);

CREATE TABLE IF NOT EXISTS user_playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playlist_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_playlist_song FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE,
    CONSTRAINT uniq_playlist UNIQUE (user_id, song_id)
);

-- Triggers to mirror ON UPDATE CURRENT_TIMESTAMP semantics
CREATE TRIGGER set_timestamp_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_timestamp_albums
BEFORE UPDATE ON albums
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_timestamp_songs
BEFORE UPDATE ON songs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_timestamp_artists
BEFORE UPDATE ON artists
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_timestamp_music_directors
BEFORE UPDATE ON music_directors
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_timestamp_user_playlists
BEFORE UPDATE ON user_playlists
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
